### PR TITLE
new icon: mariadb (original, original-wordmark)

### LINKED ISSUE #921: [ICON REQUEST]: mariaDB
### About the icon

would be nice to have mariaDB icon too :)

### Links and sources

main website: https://mariadb.org
docker website: https://hub.docker.com/_/mariadb

https://raw.githubusercontent.com/docker-library/docs/fe985dcb24154456254e252d1fa4a2b6b656ee80/mariadb/logo.png

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luizcarloscf**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #921**

## Link to prove your SVG is correct and up-to-date.

https://mariadb.com/about-us/logos/

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
It'd be great if you could add non-font versions like this, and keep the font versions like the current ones (just a plain color). What do you think? 🙂

image

**Comment by Panquesito7** [comment]
> I think this logo is actually from the MariaDB Foundation: [MariaDB Foundation](https://mariadb.org/about/#logos-and-badges).
> 
> The usage terms at [official site](https://mariadb.com/about-us/logos/):
> 
> > Basic Usage Guidelines
> > Do not rotate the MariaDB logo, choose the appropriate format (vertical or horizontal).
> > Do not change the color of the MariaDB logo, only use the versions provided on this page.
> > Be sure to scale the MariaDB logo proportionately.
> > Allow an appropriate amount of white space around the MariaDB logo.
> 
> I'm not really sure, I don't know much about the project...

Ahh, I see I see. That's fine, then. Feel free to keep it as-is. :)

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thanks! 🚀

image

image

**Review by lunatic-fox — APPROVED** [review]
Looks great to me! ✔
Thank you for this contribution! 🚀

**Pull request merged**
