### PR TITLE
update icon: ballerina (original, original-wordmark, plain, plain-wordmark, line, line-wordmark) 

### PR DESCRIPTION
**Pull request by cyberalien**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features
Fixes:
- incorrect `viewBox` and removes junk code
- stroke in `line` icons
- scaling in icons without text

**This PR closes [1544](https://github.com/devicons/devicon/issues/1544)**

## Notes
I could not find what framework or project this icon belongs to, so maybe it needs to be checked for newer version. Fixed icons as is, based on previously added icons.

### CODE REVIEW

**Comment by cyberalien** [comment]
Parsed icons again to fix issues. Previous commit had multiple paths in `plain` and `line` icons. New version matches requirements and has been tested on icomoon.

**Comment by lunatic-fox** [comment]
https://github.com/devicons/devicon/pull/1545/commits/598e22b1486637f39ed24e620ca83228c4ea87d4
- Delete `plain` and `plain-wordmark` versions and add them as aliases to `original` and `original-wordmark` versions respectively.
- Resize icons to fit the box.

**Review by Snailedlt — APPROVED** [review]
LGTM! :heavy_check_mark: 
Thank you for your contribution! :100:

**Review by lunatic-fox — APPROVED** [review]
Approved! ✔
Thank you for this contribution! 🚀

**Pull request merged**
