### PR TITLE
only check stroke for icons in devicon.json's font objects

### LINKED ISSUE #1325: [BUG] `check-bot` check `-original` icons even when they won't be added to icomoon
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Currently `check-bot` perform check operations related to icomoon specifications like the "no usage of stroke(s) attribute(s) in paths" even when the icons won't be included in the devicon font.

### Possible fixes or solutions

When an icon `-plain.svg` exist in a PR, don't check `-original.svg` the **icomoon rules**.
And also when an icon `-plain-wordmark.svg` exist in a PR, don't check `-original-wordmark.svg` the **icomoon rules**.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Snailedlt**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

**This PR closes #1325**

## Notes

Tested by pushing to master in my fork, then making a PR with an original icon containing the `stroke` attribute, and changing which icons are listed inside devicon.json's `font` object. 
Here's the PR I tested: https://github.com/Snailedlt/devicon/pull/63

### CODE REVIEW

**Comment by Snailedlt** [comment]
@BenSouchet Finally got around to adding this. Take a look if you'd like :)

**Comment by Panquesito7** [comment]
Why was this https://github.com/Snailedlt/devicon/pull/63#issuecomment-1296351707 shown? 🤔

**Review by Panquesito7 — APPROVED** [review]
I'm no Python expert but looks good to me. Thanks! 🚀
We can proceed to merge this ASAP if you like.

**Comment by Snailedlt** [comment]
@lunatic-fox you've gained a bit of python knowledge lately. I would appreciate a review from you when you have time :)

**Review by ConX — APPROVED** [review]
This looks good to me as well!  @Snailedl, thanks for working on this!

**Comment by Panquesito7** [comment]
Will be merging in a few days if no new reviews are made.
If any changes are needed, those should be done in another PR.

**Pull request merged**
