### PR TITLE
New icon: kalilinux (original, original-wordmark, plain-wordmark, line, line-wordmark)

### LINKED ISSUE #2072: [ICON REQUEST]: <Kali Linux>
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

There is a lot of people in the area of cyber security that uses Kali and want to use the icon

### Links and sources

www.kali.org

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes #2072**

## Link to prove your SVG is correct and up-to-date.

- [Kali Linux Press Pack](https://gitlab.com/kalilinux/documentation/press-pack)
- [Kali Linux Website](https://www.kali.org/)

The color `#2777ff` was selected for the font SVGs as it's the main Kali Linux color.

### CODE REVIEW

**Comment by sammorozov** [comment]
merge it please!

**Review by weh — COMMENTED** [review]
Found just a very small detail 👍

**Review by lunatic-fox — APPROVED** [review]
Great work! ✨
Thank you for this contribution! 🚀

**Review by weh — APPROVED** [review]
Looks good, thank you :)

**Pull request merged**
