### PR TITLE
new icon: almalinux (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #1826: [ICON REQUEST]: AlmaLinux
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

A Notable RHEL Fork

### Links and sources

* [Official Website](https://almalinux.org/)
* [Wikipedia](https://en.wikipedia.org/wiki/AlmaLinux)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1826**

## Link to prove your SVG is correct and up-to-date.

Main Website: https://almalinux.org/
Github: https://github.com/AlmaLinux/
Wiki: https://en.wikipedia.org/wiki/AlmaLinux

Almalinux has a whole heap of colors in the original logo; I went with `#ffffff` as the main icon color given how it's the most prominent color. I also choose `#000000` for the plain icons.

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
The paths need to be unified for the plain and plain-wordmark versions. Other than that this PR looks excellent!

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️ 
Thank you for another great contribution! 🚀

**Review by lunatic-fox — CHANGES_REQUESTED** [review]
Hello there!
Seems that the files get a little bit smaller when ungroup and unify some paths, so here are them already modified.

`original`


`original-wordmark`


> *PS: I can't commit myself on this pull request right now.*

**Review by lunatic-fox — APPROVED** [review]
Perfect! 💯
Thank you for this contribution! 🚀

**Review by weh — APPROVED** [review]
Nothing to change, Thank you :+1:

**Pull request merged**
