### PR TITLE
Add a CSS library (foundation/bootstrap) to devicon.dev demo website

### PR DESCRIPTION
**Pull request by theblobscp**
Most websites use either bootstrap or foundation.  I added both as a html comment so you can pick which one would be best.

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
@theblobscp thanks for the hint, but honestly I don't see how this would help the project? Since our demo website (devicon.dev) is up and running (sure, there's always room for improvement), how does adding a css framework - which is not used yet - helps? 

When you have a particular idea how to improve the website I'm curious to hear about it, but adding frameworks alone just increases the load time without any benefit. Maybe I'm on a false track, so please prove me wrong! 😃

**Comment by theblobscp** [comment]
Mostly due to the fact bootstrap has prebuilt classes (example d-flex), which saves the time of writing the same lines of code over and over again

**Comment by amacado** [comment]
> Mostly due to the fact bootstrap has prebuilt classes (example d-flex), which saves the time of writing the same lines of code over and over again

while that is generally true, can you point out where exactly you see the improvement in our code?

**Comment by theblobscp** [comment]
I would use the vercel thing to show differences but I was never able to get it to work

**Comment by Thomas-Boi** [comment]
Hey @theblobscp,

For our website, we've styled it without Bootstrap. There are also some angular-specific styling in there and I do not want to mess that up. 

Furthermore, while it's true that bootstrap is popular, it doesn't mean that every project, or our website, need to use it. For the devicon site, we've never use it and I don't think we need to in the foreseeable future. In this case, it's the rule of "if it's not broken, don't fix it".

I know that in programming, there seems to be things that EVERYBODY do. However, the repo is set up in a way that suit us and we have no need to change it. If you make a compelling argument for why we need bootstrap (say, a new layout), I'm willing to change my mind. For now, I'll close the PR.

**Pull request closed without merging**
