### PR TITLE
new icon: freecodecamp (original, original-wordmark)

### LINKED ISSUE #1035: Icon request: freeCode Camp
### About the icon

freeCodeCamp is a learning platform with lot's of resources for the developers.

### Links and sources

https://www.freecodecamp.org

https://en.wikipedia.org/wiki/FreeCodeCamp

https://github.com/freeCodeCamp

### Additional information

freeCodeCamp is a non-profit organization that consists of an interactive learning web platform, an online community forum, online publications and local organisations that intend to make learning web development accessible to anyone.

### PR DESCRIPTION
**Pull request by weh**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

closes #1035

## Link to prove your SVG is correct and up-to-date.

https://design-style-guide.freecodecamp.org/

### CODE REVIEW

**Comment by Snailedlt** [comment]
I'm not convinced FreeCodeCamp fits the scope of devicons. What do you think @Panquesito7?
https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F

**Comment by Panquesito7** [comment]
Right. It is to learn code, however, it is not a tool or framework.
I think we should close this PR, unless we should wait for other contributors' opinions.

Still, thanks for your contributions, @weh. 🙂

**Comment by Snailedlt** [comment]
> I'm not convinced FreeCodeCamp fits the scope of devicons. What do you think @Panquesito7? https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F

> Right. It is to learn code, however, it is not a tool or framework. I think we should close this PR, unless we should wait for other contributors' opinions.

@BenSouchet @devicons/supporter @killian-paquier
Any thoughts?

**Comment by Snailedlt** [comment]
Alright, I'm gonna close this for now.

@kilianpaquier @BenSouchet @lunatic-fox @weh 
Let me know if you feel like this should be accepted, and I'll consider re-opening :)

**Comment by lunatic-fox** [comment]
I think it should be closed, I share @Panquesito7's opinion.

**Comment by lunatic-fox** [comment]
I think it should stay closed, I share @Panquesito7's opinion.

**Pull request closed without merging**
