### PR TITLE
ADDED DARK MODE functionality

### PR DESCRIPTION
**Pull request by abhinav2712**
### **Description**
This pull request adds dark mode functionality to the web page. When the user clicks on the dark mode button, the page background color and text color will be changed to make the page easier to view in low-light conditions. The user's choice of light or dark mode is stored in the browser's local storage, so the page will remember the user's preference across sessions.

### **Changes Made**

- Added a "Dark Mode" button to the page header.
- Implemented a toggle function using JavaScript to change the background color, text color, and button icon when the user switches between light and dark mode.
- Added CSS styles for the dark mode theme.

### **Testing**
I have tested the dark mode feature on various browsers and devices to ensure compatibility and functionality.

### **Checklist**

- [x]  Tested the dark mode feature on various browsers and devices
- [x]  Reviewed the code for readability and maintainability
- [x]  Ensured the feature meets the requirements outlined in the project brief
- [ ]  Added appropriate comments to the code
- [ ]  Made the button more with the theme design

Thank you for taking your time to go through my PR, I hope to get relevant comments and improvements
Happy Hacking!

### CODE REVIEW

**Comment by lunatic-fox** [comment]
I think this is pretty neat! 🤩
However, I also think you'll need to create those modifications from `<YOUR DEVICONS FORK>:develop` to `devicons:develop`, in other words, recreate this pull request from `develop` branch.

**Comment by abhinav2712** [comment]
@lunatic-fox  Oh, do u mean pushing the branch to 'develop' branch??

**Comment by Snailedlt** [comment]
@abhinav2712 No, you need to base your branch on develop, then change the PRs "base" branch, so that it shows the diff between your branch and develop.


So in essense you need to checkout develop locally -> Make the new branch -> make the changes needed -> create a new PR from your branch to develop


```sh
git checkout develop
git pull
git checkout -b feature/your_branch_name
```

**Comment by abhinav2712** [comment]
@Snailedlt Got it , my bad....should have read the PR regulations, will fix this again, 
Thank you

**Comment by abhinav2712** [comment]
@Snailedlt Made a new PR due to some conflicts from my side, check that PR, Hence I am closing this PR

**Pull request closed without merging**
