### PR TITLE
update icon: typo3 (original, original-wordmark, plain-wordmark, line, line-wordmark)

### PR DESCRIPTION
**Pull request by weh**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

- Removed padding and optimized images
- Replaced duplicate original/plain with alias
- Added line versions

**This PR closes NONE**

Part of #1998 and #2001

### CODE REVIEW

**Review by lunatic-fox — DISMISSED** [review]
Good job! 👍🏼
Thank you for this contribution! 🚀
image
image
image
image

**Review by Snailedlt — COMMENTED** [review]
The plain and line versions are missing the fill attribute, which makes those versions black. That's fine for the font since we can change the color easily, but for the svg versions it's more difficult to change the color.
imo we should use the color from `devicon.json` as fill for all icons with a single path

@lunatic-fox I know you have some opinions on this, what do you think?

**Comment by lunatic-fox** [comment]
> The plain and line versions are missing the fill attribute, which makes those versions black. That's fine for the font since we can change the color easily, but for the svg versions it's more difficult to change the color. imo we should use the color from `devicon.json` as fill for all icons with a single path
> 
> @lunatic-fox I know you have some opinions on this, what do you think?

I got your point @Snailedlt and yeah, all this time I was considering `devicon.json` color just for font versions, but didn't consider for SVG versions. Making changes on the next commit.

**Review by lunatic-fox — APPROVED** [review]
image
image
image
image

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇

**Pull request merged**
