### PR TITLE
Release v2.8.0

### PR DESCRIPTION
**Pull request by amacado**
~~Since this version does only contain PATCHES and no MINOR nor MAJOR changes I suggest to release it as v2.7.1.~~ As soon it's released I will change the GitHub Pages to point to `master`/`docs`.

~~This pull request is stated as DRAFT since some features (#395) are missing before this new release should be published.~~

Icons
- New: bash (https://github.com/devicons/devicon/pull/415)

Features
- Merge `gh-pages` with `master` (https://github.com/devicons/devicon/issues/165)
- Auto-Update latest version (tagging) in GitHub Page (including CDN link) (https://github.com/devicons/devicon/issues/395)
- Bumps [ini](https://github.com/isaacs/ini) from 1.3.5 to 1.3.8. 
- Refactoring SVG to replace classes with inline css (https://github.com/devicons/devicon/pull/403 & https://github.com/devicons/devicon/issues/407 & https://github.com/devicons/devicon/pull/416)
- improved workflow for reviewing (`bot:peek`) (https://github.com/devicons/devicon/pull/412)

Fix
- Fix missing font icons (https://github.com/devicons/devicon/issues/248)
- Fix ISSUE_TEMPLATE icon-request isn't adding the `request:icon label (https://github.com/devicons/devicon/issues/405)

Thanks to all contributors for this release @Thomas-Boi @rawdanowiczdev @EnisMulic

### CODE REVIEW

**Comment by amacado** [comment]
@Thomas-Boi in my opinion this is ready for next release. Any additions?

**Comment by Thomas-Boi** [comment]
I'll also make a pull request to update the  `CONTRIBUTING` files. I think we should let people know of our new svg standard as mentioned [here](https://github.com/devicons/devicon/issues/407). The checking script can be added in a future release.

**Comment by Thomas-Boi** [comment]
Hi @amacado ,

I have created the `CONTRIBUTING` update PR [here](https://github.com/devicons/devicon/pull/416). 

Also, should we delete the `gh-pages` after we merge this into master?

**Comment by amacado** [comment]
> Also, should we delete the `gh-pages` after we merge this into master?

Yes, I will delete it after the merge

**Review by Thomas-Boi — COMMENTED** [review]
Everything seems fine for me. We should be able to merge this after the other PR are confirmed

**Comment by amacado** [comment]
@Thomas-Boi I think this pr is ready? Or am I missing something? I propose to publish it as v2.8.0 since we have a new icon in here (bash).

**Comment by Thomas-Boi** [comment]
Hi there,

Should we wait to get Eleventy in as well? If not, I think we can publish this release too.

**Comment by amacado** [comment]
@Thomas-Boi since there are many pending pr with new icons I would like to merge it now and have a new release once all pending pull requests are done (including Eleventy)

**Comment by Thomas-Boi** [comment]
That sounds good to me. This release has been waiting for awhile now.

**Pull request merged**
