### PR TITLE
redesign readme.md

### PR DESCRIPTION
**Pull request by amacado**
So I reworked the README to give it a cleaner, fresher look. You can check it in my [branch](https://github.com/devicons/devicon/tree/amacado/feature/update-readme).

image

Happy to hear your feedback on this! :)

### CODE REVIEW

**Review by Thomas-Boi — DISMISSED** [review]
Wow, I really like the redesign 👍. It looks professional and well-formatted. Great job amacado!

**Comment by Thomas-Boi** [comment]
Oh, I just notice one thing: 

image

What is this acronym? I am familiar with a similar one called "TL;DR", which stands for "too long; didn't read". Is this a different acronym?

**Comment by amacado** [comment]
TL;TR = To Long; To Read, but TL;DR; is fine too.. ;-)

**Comment by amacado** [comment]
@Thomas-Boi I renamed the headline to TL;DR; this is more familiar.. Thanks for pointing out. Can you review again? :)

**Review by Thomas-Boi — APPROVED** [review]
Everything looks 😄

**Pull request merged**
