### PR TITLE
New icon: Premiere pro (plain, original)

### PR DESCRIPTION
**Pull request by ezSaldana**
## Added Premiere Pro icon
I've added the plain and original Premiere Pro icons. Give it a check and let me know if there's something I should change.

### Image
Screen Shot 2020-10-24 at 16 57 38

### Issue Reference
#110

### CODE REVIEW

**Comment by amacado** [comment]
Thanks for the afford, but I'm not sure if premiere pro matches this projects description of "developer icons" (see [README.md](https://github.com/devicons/devicon/edit/master/README.md))

> Devicon aims to gather all logos representing development languages and tools

@Thomas-Boi, @konpa what do you think? Open discussion.

**Comment by ezSaldana** [comment]
I would say that just like photoshop or illustrator (icons already added), these are tools that are often used. Indirect tools but tools at the end. 🤔

**Comment by Thomas-Boi** [comment]
For me, I'm not too sure whether we should add the Premiere icons. I searched up the app and people mostly use it for video editing. This is not a programming job but I can see how some programming jobs would use it (video game, web dev,...). As stated in the After Effects PR, we also have Adobe Photoshop in our repo so I am fine with Adobe product; I'm just having issues deciding whether it's in line with our "development languages and tools" goal.

On the other hand, designers are an important part of the programming world. It makes sense that they might want to have a Premiere icon in their website/portfolio. So I think that we can accept the PR since it is technically a tool (as @ezSaldana pointed out) and some tech jobs do use it, albeit not directly related to coding. 

On a side note, we might need to work on a proper definition on what counts as "development tools". This makes me think about whether Microsoft Word or Icomoon would count as a development tool and I think right now we don't have a clear definition.

**Review by amacado — CHANGES_REQUESTED** [review]
Would you mind replacing the capital letters with lowercase? `icons/premierepro/permiere**P**ro-original.svg`, `icons/premierepro/permiere**P**ro.eps` & `icons/premierepro/permiere**Pro**-plain.svg`

This ensures our build and release process runs fluently (and it also matches our guidelines) ;-)

**Comment by ezSaldana** [comment]
> Would you mind replacing the capital letters with lowercase? `icons/premierepro/permiere**P**ro-original.svg`, `icons/premierepro/permiere**P**ro.eps` & `icons/premierepro/permiere**Pro**-plain.svg`
> 
> This ensures our build and release process runs fluently (and it also matches our guidelines) ;-)

Ok, i'm changing it!

**Review by amacado — CHANGES_REQUESTED** [review]
@ezSaldana I think there is a typo in the filenames now.. it says `permierepro-` instead `premierepro-`

**Comment by ezSaldana** [comment]
Sorry, my bad, i hope there are no more errors.

**Comment by amacado** [comment]
No worries, that's the reason why we have a review process 👍🏻

**Review by amacado — APPROVED** [review]
Looking good! :) Thanks for the contribution. I think we should soon do a new release :)

image

**Comment by ezSaldana** [comment]
You're welcome, i'm waiting for that release 😃

**Pull request merged**
