### PR TITLE
Build preparation for release v2.16.0

### PR DESCRIPTION
**Pull request by Snailedlt**
```
A huge thanks to all our maintainers and contributors for making this release possible!

 **168 New Icons**
- [update icon: apachespark (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1649) by @lunatic-fox, @luizcarloscf.
- [update icon: rabbitmq (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1625) by @Snailedlt, @luizcarloscf.
- [update icon: openstack (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1622) by @luizcarloscf.
- [update icon: helm (original, line)](https://github.com/devicons/devicon/pull/1618) by @lunatic-fox, @ConX.
- [new icon: keras (plain, plain-wordmark, line, line-wordmark, original-wordmark)](https://github.com/devicons/devicon/pull/1617) by @lunatic-fox, @ConX.
- [new icon: gazebo (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1610) by @Snailedlt, @lunatic-fox, @luizcarloscf.
- [new icon: vault (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1609) by @luizcarloscf.
- [new icon: algolia (original, original-wordmark)](https://github.com/devicons/devicon/pull/1608) by @lunatic-fox, @PantheraRed.
- [new icon: consul (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1604) by @lunatic-fox, @luizcarloscf.
- [new icon: titaniumsdk (original)](https://github.com/devicons/devicon/pull/1596) by @lunatic-fox, @m1ga.
- [update icon: qt (original)](https://github.com/devicons/devicon/pull/1595) by @lunatic-fox.
- [update icon: redux (original)](https://github.com/devicons/devicon/pull/1594) by @lunatic-fox.
- [update icon: twitter (original)](https://github.com/devicons/devicon/pull/1593) by @lunatic-fox.
- [update icon: ballerina (line, line-wordmark)](https://github.com/devicons/devicon/pull/1592) by @lunatic-fox.
- [update icon: tortoisegit (original, plain, line)](https://github.com/devicons/devicon/pull/1591) by @lunatic-fox.
- [update icon: plotly (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1589) by @lunatic-fox.
- [update icon: php (plain)](https://github.com/devicons/devicon/pull/1588) by @lunatic-fox.
- [update icon: ruby (plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1587) by @lunatic-fox.
- [update icon: podman (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1586) by @lunatic-fox.
- [update icon: mocha (original, plain)](https://github.com/devicons/devicon/pull/1584) by @lunatic-fox.
- [update icon: rust (plain)](https://github.com/devicons/devicon/pull/1581) by @lunatic-fox.
- [update icon: polygon (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1580) by @lunatic-fox.
- [new icon: githubcodespaces (original, plain)](https://github.com/devicons/devicon/pull/1574) by @lunatic-fox.
- [new icon: hardhat (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1565) by @lunatic-fox.
- [new icon: swagger (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1561) by @lunatic-fox, @yeyeto2788, @Juan Biondi.
- [new icon: cassandra (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1558) by @lunatic-fox.
- [new icon: solidjs (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1557) by @AbdelrahmanDwedar, @lunatic-fox.
- [new icon: nodemon (original, plain, line)](https://github.com/devicons/devicon/pull/1556) by @PantheraRed.
- [update icon: ballerina (original, original-wordmark, plain, plain-wordmark, line, line-wordmark) ](https://github.com/devicons/devicon/pull/1545) by @lunatic-fox, @cyberalien.
- [update icon: astro (plain-wordmark, plain, original-wordmark, original)](https://github.com/devicons/devicon/pull/1543) by @lunatic-fox, @cyberalien.
- [update icon: discordjs (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1540) by @lunatic-fox.
- [update icon: ember (original, original-wordmark, plain)](https://github.com/devicons/devicon/pull/1539) by @Snailedlt, @lunatic-fox.
- [update icon: grails (original, plain)](https://github.com/devicons/devicon/pull/1538) by @lunatic-fox.
- [update icon: kaggle (original-wordmark)](https://github.com/devicons/devicon/pull/1537) by @lunatic-fox.
- [update icon: safari (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1536) by @lunatic-fox.
- [update icon: phoenix (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1535) by @lunatic-fox.
- [update icon: bootstrap (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1534) by @lunatic-fox, @cyberalien.
- [update icon: yii (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1533) by @lunatic-fox, @cyberalien.
- [update icon: php (original, plain)](https://github.com/devicons/devicon/pull/1531) by @Snailedlt, @lunatic-fox, @cyberalien.
- [update icon: apache (original, plain, line, original-wordmark, plain-wordmark, line-wordmark)](https://github.com/devicons/devicon/pull/1527) by @lunatic-fox, @cyberalien.
- [update icon: denojs (original, original-wordmark)](https://github.com/devicons/devicon/pull/1526) by @lunatic-fox, @PantheraRed.
- [update icon: vscode (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1524) by @lunatic-fox, @cyberalien.
- [new icon: corejs (original, original-wordmark)](https://github.com/devicons/devicon/pull/1514) by @Snailedlt, @PantheraRed.
- [new icon: pfsense (original, original-wordmark)](https://github.com/devicons/devicon/pull/1508) by @lunatic-fox, @yeyeto2788, @Juan Biondi.
- [new icon: gitbook (original, original-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1507) by @PantheraRed.
- [update icon: jira (plain,plain-wordmark)](https://github.com/devicons/devicon/pull/1501) by @lunatic-fox.
- [new icon: photonengine (original,plain)](https://github.com/devicons/devicon/pull/1499) by @Snailedlt, @lunatic-fox, @yeyeto2788, @Juan Biondi.
- [new icon: jule (original, original-wordmark)](https://github.com/devicons/devicon/pull/1498) by @lunatic-fox.
- [new icon: rollup (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1497) by @PantheraRed.
- [update icon: tailwindcss (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1493) by @lunatic-fox, @theabhayprajapati.
- [new icon: hadoop (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1488) by @Snailedlt, @MAGistR-bit, @Thomas-Boi, @lunatic-fox, @amacado.
- [new icon: vitejs (original, plain)](https://github.com/devicons/devicon/pull/1473) by @AcmeGamers, @kilianpaquier, @Thomas-Boi, @lunatic-fox, @amacado.
- [new icon: vite (original, original-wordmark)](https://github.com/devicons/devicon/pull/1472) by @AcmeGamers, @lunatic-fox, @kilianpaquier.
- [new icon: jiraalign (original,plain,original-wordmark,plain-wordmark)](https://github.com/devicons/devicon/pull/1468) by @yeyeto2788.
- [new icon: p5js (original)](https://github.com/devicons/devicon/pull/1465) by @lunatic-fox, @yeyeto2788.
- [new icon: githubactions (original,plain)](https://github.com/devicons/devicon/pull/1463) by @lunatic-fox, @yeyeto2788.
- [new icon: bun (original)](https://github.com/devicons/devicon/pull/1462) by @lunatic-fox, @AmreshSinha.
- [new icon: tauri (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1457) by @lunatic-fox, @weh.
- [new icon: wasm (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1456) by @lunatic-fox, @weh.
- [new icon: knexjs (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1452) by @lunatic-fox.
- [new icon: reactbootstrap (original)](https://github.com/devicons/devicon/pull/1451) by @lunatic-fox.
- [new icon: tex (original)](https://github.com/devicons/devicon/pull/1449) by @lunatic-fox.
- [new icon: yaml (original, plain)](https://github.com/devicons/devicon/pull/1448) by @lunatic-fox.
- [new icon: influxdb (original, original-wordmark)](https://github.com/devicons/devicon/pull/1447) by @Panquesito7.
- [new icon: playwright (original, plain)](https://github.com/devicons/devicon/pull/1437) by @oguzakif.
- [new icon: qwik (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1435) by @Panquesito7, @AmreshSinha.
- [new icon: splunk (original-wordmark)](https://github.com/devicons/devicon/pull/1433) by @Snailedlt, @weh.
- [new icon: akka (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1431) by @Panquesito7, @ozanuslan.
- [new icon: llvm (original, plain)](https://github.com/devicons/devicon/pull/1428) by @weh.
- [new icon: okta (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1427) by @Snailedlt, @weh.
- [new icon: vercel (original, original-wordmark)](https://github.com/devicons/devicon/pull/1419) by @Panquesito7.
- [new icon: livewire (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1415) by @Panquesito7.
- [new icon: realm (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1413) by @lunatic-fox.
- [new icon: apacheairflow (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1412) by @lunatic-fox, @Panquesito7.
- [new icon: cairo (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1408) by @lunatic-fox.
- [new icon: djangorest (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1407) by @Snailedlt, @lunatic-fox.
- [update icon: gitlab (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1404) by @PantheraRed.
- [new icon: apl (original, plain)](https://github.com/devicons/devicon/pull/1402) by @lunatic-fox.
- [new icon: vyper (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1401) by @lunatic-fox.
- [new icon: stata (original-wordmark)](https://github.com/devicons/devicon/pull/1400) by @lunatic-fox.
- [new icon: vala (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1397) by @lunatic-fox.
- [new icon: pyscript (original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1396) by @lunatic-fox.
- [new icon: clarity (original, plain)](https://github.com/devicons/devicon/pull/1393) by @lunatic-fox.
- [new icon: renpy (original, plain) ](https://github.com/devicons/devicon/pull/1392) by @lunatic-fox.
- [new icon: cosmosdb (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1386) by @Panquesito7.
- [new icon: reach (original, plain)](https://github.com/devicons/devicon/pull/1380) by @RyanKoech.
- [new icon: sema (original, original-wordmark)](https://github.com/devicons/devicon/pull/1373) by @Panquesito7.
- [new icon: gitpod (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1372) by @Panquesito7.
- [new icon: materializecss (original, plain)](https://github.com/devicons/devicon/pull/1363) by @AbdelrahmanDwedar, @Panquesito7, @Thomas-Boi, @lunatic-fox, @amacado.
- [new icon: v8 (original, plain)](https://github.com/devicons/devicon/pull/1354) by @ngdream, @Snailedlt.
- [new icon: astro (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1350) by @Panquesito7, @amacado, @szmazhr, @Thomas-Boi.
- [new icon: norg (original, plain)](https://github.com/devicons/devicon/pull/1346) by @dvchoudh, @amacado, @Thomas-Boi.
- [new icon: cloudflareworkers (plain, plain-wordmark, original, original-wordmark)](https://github.com/devicons/devicon/pull/1326) by @BenSouchet.
- [new icon: alpinejs (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1324) by @BenSouchet.
- [new icon: matplotlib (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1323) by @BenSouchet.
- [new icon: qodana (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1322) by @Kilian PAQUIER.
- [new icon: ktor (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1321) by @Kilian PAQUIER.
- [new icon: fastify (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1320) by @BenSouchet.
- [update icon: pycharm (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1319) by @Kilian PAQUIER.
- [update icon: rubymine (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1318) by @Kilian PAQUIER.
- [update icon: webstorm (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1317) by @Kilian PAQUIER.
- [update icon: rider (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1316) by @Kilian PAQUIER.
- [update icon: kotlin (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1315) by @Kilian PAQUIER.
- [new icon: goland (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1314) by @Kilian PAQUIER.
- [new icon: dataspell (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1313) by @Kilian PAQUIER.
- [new icon: awk (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1312) by @Snailedlt.
- [new icon: nano (original, original-wordmark)](https://github.com/devicons/devicon/pull/1310) by @Snailedlt, @Panquesito7, @BenSouchet.
- [new icon: json (original, plain)](https://github.com/devicons/devicon/pull/1309) by @BenSouchet.
- [new icon: opencl (original, plain)](https://github.com/devicons/devicon/pull/1307) by @BenSouchet.
- [new icon: moleculer (original, plain)](https://github.com/devicons/devicon/pull/1296) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: datagrip (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1292) by @Kilian PAQUIER, @kilianpaquier.
- [update icon: clion (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1291) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: azuredevops (original, plain)](https://github.com/devicons/devicon/pull/1289) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: quasar (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1266) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: faunadb (original, original-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1265) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: apachespark (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1261) by @luizcarloscf.
- [new icon: dbeaver (original, plain)](https://github.com/devicons/devicon/pull/1245) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: sqldeveloper (original, plain)](https://github.com/devicons/devicon/pull/1244) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: unifiedmodelinglanguage (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1241) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: angular (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1240) by @gabrielfins.
- [new icon: quarkus (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1239) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: opentelemetry (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1238) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: karatelabs (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1236) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: jaegertracing (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1235) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: envoy (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1228) by @Kilian PAQUIER.
- [new icon: hibernate (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1227) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: nhibernate (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1226) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: liquibase (original, original-wordmark)](https://github.com/devicons/devicon/pull/1224) by @Kilian PAQUIER.
- [new icon: powershell (original, plain)](https://github.com/devicons/devicon/pull/1219) by @BenSouchet.
- [new icon: postcss (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1212) by @canaleal.
- [update icon: laravel (original) ](https://github.com/devicons/devicon/pull/1208) by @amacado, @antoninhrlt, @Thomas-Boi.
- [new icon: streamlit (original, plain, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1207) by @canaleal.
- [new icon: ballerina (original, plain, line, original-wordmark, plain-wordmark, line-wordmark)](https://github.com/devicons/devicon/pull/1205) by @zachary-cauchi.
- [new icon: Codeac (original)](https://github.com/devicons/devicon/pull/1203) by @michal-simon.
- [new icon: openstack (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1137) by @luizcarloscf.
- [new icon: plotly (original, original-wordmark)](https://github.com/devicons/devicon/pull/1134) by @luizcarloscf.
- [new icon: rabbitmq (original, original-wordmark)](https://github.com/devicons/devicon/pull/1133) by @luizcarloscf.
- [new icon: helm (original)](https://github.com/devicons/devicon/pull/1132) by @luizcarloscf.
- [new icon: vsphere (original, original-wordmark)](https://github.com/devicons/devicon/pull/1123) by @thehedgefrog.
- [new icon: harvester (original, original-wordmark)](https://github.com/devicons/devicon/pull/1122) by @thehedgefrog.
- [new icon: k3os (original, original-wordmark)](https://github.com/devicons/devicon/pull/1121) by @thehedgefrog.
- [new icon: rancher (original, original-wordmark)](https://github.com/devicons/devicon/pull/1120) by @thehedgefrog.
- [new icon: antdesign (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1119) by @jusuchin85.
- [new icon: xml (original)](https://github.com/devicons/devicon/pull/1118) by @jusuchin85.
- [new icon: junit (original, original-wordmark)](https://github.com/devicons/devicon/pull/1117) by @jusuchin85.
- [new icon: purescript (original, original-wordmark)](https://github.com/devicons/devicon/pull/1116) by @jusuchin85.
- [new icon: scalingo (original, original-wordmark)](https://github.com/devicons/devicon/pull/1115) by @jusuchin85.
- [new icon: nimble (original, plain)](https://github.com/devicons/devicon/pull/1114) by @jusuchin85, @Panquesito7.
- [new icon: nim (original, original-wordmark)](https://github.com/devicons/devicon/pull/1113) by @jusuchin85.
- [new icon: vertx (original, original-wordmark)](https://github.com/devicons/devicon/pull/1112) by @jusuchin85.
- [new icon: mobx (original, plain)](https://github.com/devicons/devicon/pull/1111) by @jusuchin85.
- [new icon: openapi (original, original-wordmark)](https://github.com/devicons/devicon/pull/1110) by @jusuchin85.
- [new icon: contao (original, original-wordmark)](https://github.com/devicons/devicon/pull/1109) by @jusuchin85.
- [new icon: jekyll (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1108) by @jusuchin85.
- [new icon: rider (original, plain-wordmark)](https://github.com/devicons/devicon/pull/1106) by @thehedgefrog.
- [new icon: portainer (original, original-wordmark)](https://github.com/devicons/devicon/pull/1105) by @thehedgefrog.
- [new icon: maven (plain, plain-wordmark, original, original-wordmark) ](https://github.com/devicons/devicon/pull/1103) by @jusuchin85.
- [new icon: mongoose (original, original-wordmark)](https://github.com/devicons/devicon/pull/1102) by @jusuchin85.
- [new icon: clion (plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1101) by @jusuchin85.
- [new icon: ros (original, original-wordmark)](https://github.com/devicons/devicon/pull/1100) by @jusuchin85.
- [new icon: fortran (original)](https://github.com/devicons/devicon/pull/1098) by @jusuchin85.
- [new icon: cypressio (original, original-wordmark)](https://github.com/devicons/devicon/pull/1097) by @jusuchin85.
- [new icon: emacs (original)](https://github.com/devicons/devicon/pull/1096) by @jusuchin85.
- [update icon: opensuse (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1095) by @jusuchin85.
- [new icon: sanity (original)](https://github.com/devicons/devicon/pull/1094) by @JorchCortez, @Panquesito7.
- [new icon: archlinux (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1088) by @jusuchin85.
- [new icon: Axios (plain,plain-wordmark)](https://github.com/devicons/devicon/pull/1087) by @JorchCortez.
- [new icon: ghost (original, original-wordmark)](https://github.com/devicons/devicon/pull/1086) by @jusuchin85.

 **56 New Features**
- [Remove unicode chars from `devicon.json`](https://github.com/devicons/devicon/pull/1652) by @Snailedlt.
- [Update readme.md](https://github.com/devicons/devicon/pull/1641) by @Ishaan2053, @amacado, @Panquesito7, @Thomas-Boi.
- [fix: remove duplicate `tauri` icon entry](https://github.com/devicons/devicon/pull/1636) by @mztnnrt.
- [Update README.md](https://github.com/devicons/devicon/pull/1633) by @Ishaan2053, @amacado, @Panquesito7, @Thomas-Boi.
- [Bugfix/update `devicon.json` and `tags-enum.json`](https://github.com/devicons/devicon/pull/1582) by @lunatic-fox.
- [Improve the issue templates](https://github.com/devicons/devicon/pull/1515) by @Snailedlt.
- [add feature: vs code extension recommendations](https://github.com/devicons/devicon/pull/1495) by @lunatic-fox.
- [add feature: vs code intellisense to `devicon.json`](https://github.com/devicons/devicon/pull/1487) by @lunatic-fox.
- [Bugfix/fix in devicon.json](https://github.com/devicons/devicon/pull/1485) by @lunatic-fox.
- [Check if PR base is develop](https://github.com/devicons/devicon/pull/1460) by @Snailedlt, @lunatic-fox.
- [Bugfix/fix in devicon.json](https://github.com/devicons/devicon/pull/1454) by @lunatic-fox.
- [Improve the feature request template](https://github.com/devicons/devicon/pull/1416) by @Panquesito7.
- [add feature:icon and enhancement labels automatically](https://github.com/devicons/devicon/pull/1411) by @Snailedlt.
- [Feature/sort devicon json and add sort check](https://github.com/devicons/devicon/pull/1405) by @Snailedlt, @lunatic-fox.
- [Minor template/stale message improvements](https://github.com/devicons/devicon/pull/1381) by @Panquesito7.
- [docs: improve contributing deprecation notice](https://github.com/devicons/devicon/pull/1367) by @Panquesito7.
- [Add editorconfig file and cleanup `devicon.json` bad formatting](https://github.com/devicons/devicon/pull/1364) by @BenSouchet.
- [Improve the `README.md` file](https://github.com/devicons/devicon/pull/1362) by @Panquesito7.
- [Improve the Discord community text](https://github.com/devicons/devicon/pull/1347) by @Panquesito7.
- [updated links to contributing guidelines](https://github.com/devicons/devicon/pull/1333) by @Snailedlt.
- [Add alphabetical ordering of `devicon.json` to PR checklist](https://github.com/devicons/devicon/pull/1332) by @Snailedlt.
- [Bugfix/replace code of conduct content with link](https://github.com/devicons/devicon/pull/1331) by @Snailedlt, @Panquesito7.
- [new icon: cloudflare (plain, plain-wordmark, original, original-wordmark)](https://github.com/devicons/devicon/pull/1298) by @BenSouchet.
- [new icon: ohmyzsh (original, plain)](https://github.com/devicons/devicon/pull/1297) by @BenSouchet.
- [update icon: phpstorm (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1294) by @Kilian PAQUIER.
- [update icon: intellij (original, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1293) by @Kilian PAQUIER.
- [new icon: azuresqldatabase (original, plain)](https://github.com/devicons/devicon/pull/1290) by @Kilian PAQUIER.
- [new icon: lumen (original, plain)](https://github.com/devicons/devicon/pull/1288) by @Kilian PAQUIER, @kilianpaquier.
- [Feature/convert style elements to attributes](https://github.com/devicons/devicon/pull/1276) by @Snailedlt.
- [new icon: capacitor (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1274) by @Kilian PAQUIER, @kilianpaquier.
- [update icon: unity (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/1273) by @Snailedlt, @Kilian PAQUIER.
- [update icon: cplusplus (original, plain, line)](https://github.com/devicons/devicon/pull/1270) by @Kilian PAQUIER.
- [update icon: amazonwebservices (original-wordmark, plain-wordmark, line-wordmark)](https://github.com/devicons/devicon/pull/1269) by @Kilian PAQUIER.
- [update icon: vuetify (original, plain, line)](https://github.com/devicons/devicon/pull/1268) by @Kilian PAQUIER.
- [new icon: eclipse (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1258) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: beats (original, plain)](https://github.com/devicons/devicon/pull/1257) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: logstash (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1256) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: elasticsearch (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1255) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: kibana (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/1254) by @Kilian PAQUIER.
- [new icon: sonarqube (original, original-wordmark)](https://github.com/devicons/devicon/pull/1250) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: traefikmesh (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1248) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: traefikproxy (original, original-wordmark, plain-wordmark)](https://github.com/devicons/devicon/pull/1247) by @Kilian PAQUIER, @kilianpaquier.
- [new icon: poetry (original, plain)](https://github.com/devicons/devicon/pull/1243) by @Kilian PAQUIER, @kilianpaquier.
- [fix: add `original-wordmark` aliases for Liquibase](https://github.com/devicons/devicon/pull/1242) by @Panquesito7.
- [new icon: postman (original, original-wordmark)](https://github.com/devicons/devicon/pull/1237) by @Kilian PAQUIER, @kilianpaquier.
- [update icon: svelte-original.svg (original)](https://github.com/devicons/devicon/pull/1201) by @amacado, @canaleal, @Thomas-Boi.
- [Convert Style Elements to Attributes](https://github.com/devicons/devicon/pull/1169) by @maltejur.
- [update icon: tensorflow (original-wordmark, line-wordmark)](https://github.com/devicons/devicon/pull/1168) by @maltejur.
- [add altnames #1165](https://github.com/devicons/devicon/pull/1167) by @Snailedlt.
- [Bump minimist from 1.2.5 to 1.2.6](https://github.com/devicons/devicon/pull/1141) by @dependabot[bot], @amacado, @Thomas-Boi.
- [new icon: clion (original)](https://github.com/devicons/devicon/pull/1107) by @jusuchin85.
- [Sort entries in devicon.json alphabetically](https://github.com/devicons/devicon/pull/1090) by @jusuchin85.
- [Fix checkbot's check version issue](https://github.com/devicons/devicon/pull/1089) by @Thomas-Boi.
- [Build preparation for release v2.15.1](https://github.com/devicons/devicon/pull/1085) by @amacado.
- [Fix issue with npm publish script](https://github.com/devicons/devicon/pull/1084) by @amacado, @Thomas-Boi.
- [fix npm publish workflow](https://github.com/devicons/devicon/pull/1083) by @amacado, @Thomas-Boi.
```

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Amazing! Thanks to all those who contributed. 🎉 🎉 🎉

**Comment by Snailedlt** [comment]
I noticed that there are a lot of icons mislabeled as features, is it because they weren't labeled? 🤔

**Comment by Panquesito7** [comment]
Something completely unrelated: this is something important that didn't build properly. If we don't have this, the new icons won't be shown. Guess there are some faulty icons. 🤔
https://github.com/devicons/devicon/actions/runs/4078484614/jobs/7028748346#step:8:14

**Comment by Snailedlt** [comment]
As pointed out by @lunatic-fox on discord, the build doesn't work because the nano icon is too big (see #1613). This should be fixed in #1619 , so we need merge that PR before we can re-build and re-do the release.
Lunatic confirmed that the font builds correctly after the icon was fixed, by uploading the modified [icomoon.json](https://raw.githubusercontent.com/devicons/devicon/4ea3f7d878ca46c1af059fcc1e8cde0bf58f9c10/icomoon.json) to icomoon. As you can see in the preview, the font preview works now:
image


ref: https://discord.com/channels/822523363884924969/885242183207223346/1071039133327302676

**Comment by Snailedlt** [comment]
Closing the issue for reasons explaiend in my previous comment

**Pull request closed without merging**
