### PR TITLE
Latest os

### PR DESCRIPTION
**Pull request by theblobscp**
Updated workflows to use the latest verison of the os

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thank you for your contribution! 😄👍

**Comment by theblobscp** [comment]
Thanks! But also sorry for triggering like 10 different workflows on my pr

**Comment by Panquesito7** [comment]
> sorry for triggering like 10 different workflows

It's alright. 🙂

**Comment by Thomas-Boi** [comment]
Hi @theblobscp,

Unfortunately, I don't think we can accept this PR. The current OS versions are locked for compatibility reasons and ensures that the build scripts work in all cases (a bit like a Docker container). 

For example, `windows-latest` will always have the latest change, which can be `windows-2021` or `windows-2030` in the future. However, `windows-2030` might function differently than `windows-2019` and could break the workflow. We already know `windows-2019` works and as long as GitHub provides the OS image, the workflow will also work. Thus, rather than forcing us to change every time a new OS comes out, we can keep using the current script until it's no longer supported.

I'll close this PR for now but I'm willing to reopen if you make good points for changing to latest OSes.

**Comment by theblobscp** [comment]
Oh ok. Well, let's just hope windows has good backwards compatibility then because I can't script at all.

**Pull request closed without merging**
