### PR TITLE
new icon: prolog (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #1761: [ICON REQUEST]: Prolog
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Prolog icon

### Links and sources

https://iconduck.com/icons/101705/prolog
https://kordamp.org/ikonli/cheat-sheet-devicons.html

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Gautam25Raj**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1761**

## Link to prove your SVG is correct and up-to-date.
https://www.swi-prolog.org/icons/vector/swipl-logo.svg

### CODE REVIEW

**Review by lunatic-fox — CHANGES_REQUESTED** [review]
Hello there! 👋🏼
Same issue that happened here: https://github.com/devicons/devicon/pull/1777#pullrequestreview-1454815677

The only difference should be the branch name, perhaps `add_prolog`. And `devicon.json` entry:
```json
    {
        "name": "prolog",
        "altnames": [
            "swi-prolog"
        ],
        "tags": [
            "programming",
            "logic"
        ],
        "versions": {
            "svg": [
                "original",
                "original-wordmark",
                "plain",
                "plain-wordmark"
            ],
            "font": [
                "plain",
                "plain-wordmark"
            ]
        },
        "color": "#F46C30",
        "aliases": []
    },
```

The icons are great, but if you can expand proportionally the `original` and the current `plain-wordmark` icons, in order to remove unnecessary padding, it would be awesome.

You'll also need to swap the name of `plain` and `plain-wordmark` files.

Wish for the best! 🚀

**Comment by lunatic-fox** [comment]
Hello again @Gautam25Raj and @dotarjun! 👋🏼

I noticed that, for some reason, both of you don't have the `develop` branch on your forked repositories. So, in order to follow the last instructions that I suggested you'll need to add this branch. Here are the steps:

### Step 1
- Go to your forked repository and click on this arrow near the current branch name.
- Then click on `View all branches`.


### Step 2
- Click on `New branch`.
2023-06-01_10h27_32

### Step 3
- On `Branch name` type `develop`.
- On `Branch source` select `devicons/devicon`.
- Right below search for `develop` branch and select it.
- After that click on `Create branch`.
2023-06-01_10h30_34
- Now you have the `develop` branch in your remote repository!

After those steps, in order to access it locally on your machine, you'll need to run it once:
```bash
git checkout -b develop origin/develop
```
Now you can create another branches from `develop` branch. For instance:
```bash
git checkout develop      # Go to "develop" branch.
git branch my_new_icon    # Create a "my_new_icon" branch.
git checkout my_new_icon  # Go to "my_new_icon" branch.
```

Also remember that some other contributions are merged to `devicons/develop` and your `develop` branch can be outdated. Therefore, you can use these commands below to update your local and remote `develop` branch in one go.

```bash
git checkout develop                # Go to "develop" branch.
git merge upstream/develop develop  # Update your "develop" branch with "devicons:develop".
git push origin                     # Push the update to your remote "develop" branch.
```

See ya! ✌🏼

**Comment by lunatic-fox** [comment]
> Thank you soo much for this reply. I was really looking into solutions that how I should move forward.

No problem! 👍🏼

**Comment by Gautam25Raj** [comment]
> No problem! 👍🏼

Should I close this PR and create a new one?

**Comment by lunatic-fox** [comment]
> > No problem! 👍🏼
> 
> Should I close this PR and create a new one?

Better do after you create the other one. 🙂

**Pull request closed without merging**
