### PR TITLE
new icon: fiber (original, plain, line)

### LINKED ISSUE #1971: [ICON REQUEST]: Fiber
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Fiber is a Go web framework built on top of Fasthttp, the fastest HTTP engine for Go. It's designed to ease things up for fast development with zero memory allocation and performance in mind.

### Links and sources

- [Github](https://github.com/gofiber/fiber)
- [Fiber SVG](https://gofiber.io/assets/images/logo.svg)
- [Github Branding](https://github.com/gofiber/fiber/blob/master/.github/testdata/fs/img/fiber.png)

### Additional information

There does not exist any logos without the `FIBER` wording. As such, use the provided SVG for all SVG versions. 3 SVGs (original, plain, line) can be created, with the wordmark versions added as Aliases in the Devicon.json file.

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1971**

## Link to prove your SVG is correct and up-to-date.

- [Github](https://github.com/gofiber/fiber)
- [Fiber SVG](https://gofiber.io/assets/images/logo.svg)
- [Github Branding](https://github.com/gofiber/fiber/blob/master/.github/testdata/fs/img/fiber.png)

The original, plain, and line svgs can be used for the wordmarks using aliases. 
The color `#00acd7` was selected for the font SVGs as it's the main Go Fiber color.

### CODE REVIEW

**Review by weh — APPROVED** [review]
LGTM :+1:

**Comment by Ryrden** [comment]
Why hasn't this PR been merged yet?

right now I need this icon.

**Comment by Dhruv9449** [comment]
Really wish this PR gets merged, I need the fiber icon for quite a few projects

**Review by Snailedlt — APPROVED** [review]
LGTM! ✅

**Comment by Ryrden** [comment]
Finally! If the svg format is wrong I can open another pull request to fix it after the merge because I noticed I couldn't commit to this pull request.

**Comment by Snailedlt** [comment]
@Ryrden looks good to me. Did you have anything in particular in mind?

**Comment by Ryrden** [comment]
I say that because the `github-actions bot` says the SVG format is wrong. 

What I have in mind is to fix this if needed

**Comment by Snailedlt** [comment]
Ahh, yeah it's just complaining about the devicon.json not being sorted correctly. It's because some other PR has put the devicon.json entry at the wrong spot, so it's complaining on every PR atm.
So nothing needs to be fixed on your end :)

**Comment by Ryrden** [comment]
Happy to know, eager for the next release! Thanks

**Pull request merged**
