### PR TITLE
update icon: Discord (Latest)

### PR DESCRIPTION
**Pull request by vikash2806**
# **New feature section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *New Feature: a brief description of feature*

## This PR fixes
The discord icon in the buttonLink section of the page is updated with latest discord logo considering the bug #907 

This new logo style matches the primary colour theme of Devicon ```#60be86```, which matches with other icons within  the section.

## Present Discord buttonLink design
Screenshot 2022-02-06 at 12 03 34 AM
 The logo is outdated.
 doesn't match colour scheme of the website.

 ## New Discord buttonLink design
Screenshot 2022-02-06 at 12 04 44 AM

The new logo is latest Discord logo. [verify here](https://discord.com/branding)
The new logo is matched with colour Scheme of the website with ```#60be86```

## Notes

This pull request is to resolve issue #907.

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Hey there! Sorry about your effort, but we already fixed the Discord logo in #909. Although I like how it matches the color of the GitHub icon. What do you think, @Thomas-Boi?

**Comment by Thomas-Boi** [comment]
I agree @Panquesito7. Since the logo has already been fixed,  this PR would be redundant. Thank you very much for your work though

**Comment by Panquesito7** [comment]
> I agree @Panquesito7. Since the logo has already been fixed, this PR would be redundant. Thank you very much for your work though

Hmm, what if we accept this PR? 😅 I like how the logo matches the GitHub icon. What do you think? Thanks. :)

**Comment by vikash2806** [comment]
> I agree @Panquesito7. Since the logo has already been fixed, this PR would be redundant. Thank you very much for your work though

@Thomas-Boi thankyour. Perhaps you should consider updating the colour scheme of the buttonLinks for Discord. and also closing the bug #907.

**Comment by Thomas-Boi** [comment]
> > I agree @Panquesito7. Since the logo has already been fixed, this PR would be redundant. Thank you very much for your work though
> 
> Hmm, what if we accept this PR? 😅 I like how the logo matches the GitHub icon. What do you think? Thanks. :)

Do you mean the color or the shape? I'm fine with either one.

**Comment by Thomas-Boi** [comment]
Also, if we do accept this PR, perhaps it can be made by rebasing our current develop. This PR contains commits from the vuetify PR, which might duplicate some stuff

**Comment by Panquesito7** [comment]
> Also, if we do accept this PR, perhaps it can be made by rebasing our current develop. This PR contains commits from the vuetify PR, which might duplicate some stuff

Fixed now. :)

**Review by Panquesito7 — APPROVED** [review]

**Comment by vikash2806** [comment]
@Thomas-Boi @Panquesito7 Thank you. I'am glad Devicon is accepting my new changes.

**Review by Thomas-Boi — APPROVED** [review]

**Pull request merged**
