### PR TITLE
new icon: chartjs (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #1822: [ICON REQUEST]: Chart.js
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Flexible JavaScript charting library for the modern web

### Links and sources

https://www.chartjs.org/img/chartjs-logo.svg

### Additional information

**Open source**
Chart.js is a community maintained project, contributions welcome!

**8 Chart types**
Visualize your data in 8 different ways; each of them animated and customisable.

**HTML5 Canvas**
Great rendering performance across all modern browsers (IE11+).

**Responsive**
Redraws charts on window resize for perfect scale granularity.

### PR DESCRIPTION
**Pull request by weh**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes**

closes #1822 

## Link to prove your SVG is correct and up-to-date.

https://www.chartjs.org/

### CODE REVIEW

**Review by canaleal — APPROVED** [review]
Nice, thank you for the contribution.
Just optimized and combined the plain svg paths.

**Comment by weh** [comment]
optimized with correct svgomg options this time, and rebased to current develop branch

**Review by canaleal — DISMISSED** [review]
Great stuff. LGTM

**Review by canaleal — APPROVED** [review]
Excellent work.

**Pull request merged**
