### PR TITLE
New icon: after effects (plain, original)

### PR DESCRIPTION
**Pull request by ezSaldana**
## Added After Effects icon
I've added the plain and original After Effects icons. Give it a check and let me know if there's something I should change.

### Image
afterEffects-icons-example

### Issue Reference
#110

### CODE REVIEW

**Comment by amacado** [comment]
Thanks for the afford, but I'm not sure if after affects matches this projects description of "developer icons" (see [README.md](https://github.com/devicons/devicon/edit/master/README.md))

> Devicon aims to gather all logos representing development languages and tools

@Thomas-Boi, @konpa what do you think? Open discussion.

**Comment by Thomas-Boi** [comment]
I think that we can accept the After Effects icons. I searched up the app and some people use it for video game development (which is a programming job). We also have Adobe Photoshop in our repo so I think we can accept Adobe apps (as long as it's used for tech jobs)

**Review by amacado — CHANGES_REQUESTED** [review]
Same as in #337: Please lowercase all filenames to match our conventions :)

**Review by amacado — APPROVED** [review]
Looking good to me! :) Thanks for the contribution @ezSaldana 

image

**Comment by ezSaldana** [comment]
Not at all!

**Pull request merged**
