### PR TITLE
New Icon: Jenkins (line, original, plain)

### LINKED ISSUE #306: Icon request: Jenkins
### About the icon

[Jenkins](https://www.jenkins.io/) is a very popular open source automation server, commonly used for CI/CD.

### Links

The main Jenkins website has a whole artwork section [here](https://www.jenkins.io/artwork/), which has a link to a SVG of the official logo: https://www.jenkins.io/images/logos/jenkins/jenkins.svg

### Preview

Jenkins

### PR DESCRIPTION
**Pull request by tariq86**
# Fixes #306

This PR adds the Jenkins logo in three formats:

### Original Format
jenkins-original

### Line Format
jenkins-line

### Plain Format
jenkins-plain

### CODE REVIEW

**Comment by tariq86** [comment]
I tried uploading my new SVGs to Icomoon, but the font icons are blank...this is my first time creating an icon, so I'm not sure why. Any pointers?

**Comment by tariq86** [comment]
I think I got it!

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by tariq86** [comment]
@Thomas-Boi merge complete! Let me know if you need anything else

**Comment by Thomas-Boi** [comment]
Hey tariq,

Thank you for getting back to us so quickly. Unfortunately, we are running into a few bugs with our build process. We are fixing it ASAP and we will get back to you when we have a solution

**Comment by Thomas-Boi** [comment]
Hi @tariq86,

We have managed to fix the bugs from the last commit. Can you try to merge develop into your branch again, please?

**Comment by tariq86** [comment]
done!

**Comment by Thomas-Boi** [comment]
Hey @tariq,

Good job on the icons! Here is what it looks like (top left)

image

I actually check your icons manually due to an issue with the script. It turned out to be an async bug but since I already have the icons, I just check them myself.

I'll merge your icons into the repo :) They won't be build into icons yet since we are going to batch builds together. However, the svgs will be there.

Thanks for your icons and welcome to Devicons!

**Comment by Thomas-Boi** [comment]
Hey @tariq86,

I just tested building the icons. Unfortunately, I forgot to remove the colors during my manual test. If I do so, your icons look like this (top left):

image

The black out one is the `jenkins-plain` icon. We have to remove all colors from the icons so that they only use one color code each. 

I apologize for the false positive. Due to this issue, I'll remove the `jenkins-plain` icon from the `font` version in the `devicon.json`. This means that the SVG is still available but the font version won't be. 

If possible, can you remove all colors from the `jenkins-plain` svg so that it's only black and white? I like what you did and you are very close to having a proper icon. Once you have it, you can then open another PR into Devicon where we will check it and most likely merge it into the repo.

**Comment by tariq86** [comment]
OK I can give that a shot now! I'm new to creating SVGs but I think I can get it

**Comment by tariq86** [comment]
Are the dimensions of the SVGs okay? I noticed that the ones I added don't take up the full browser window when you view them directly like the other logos do. For example:

The Apache logo fills the whole browser window:
[Apache Logo](https://raw.githubusercontent.com/devicons/devicon/master/icons/apache/apache-original.svg)

But my new Jenkins logo doesn't:
[Jenkins Logo](https://raw.githubusercontent.com/tariq86/devicon/feature/306-jenkins/icons/jenkins/jenkins-original.svg)

**Comment by Thomas-Boi** [comment]
Hey tariq,

I don't think the size in the browser matters. Our standard is that all SVGs must be in 0X0X128X128 view box. Besides that, there is no other restrictions.

I also would recommend opening a new PR since this one is already merged. Once that is done, I will peek at your icon and we'll see what happens.

You can also manually test your icon using the [this site](https://icomoon.io/app/#/select). Press the hamburger input on the page then select "Import To Set" to add your SVG.

I look forward to seeing your icon :)

**Pull request merged**
