### PR TITLE
Added Amber Framework and DotNet Core (not dotnet) Icons

### PR DESCRIPTION
**Pull request by kirinnee**

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hello there,

We notice that this PR has been inactive for awhile now. It would be a waste of your time and effort if we just close this PR and throw away the SVGs in here. Thus, 1 month from now, if this PR remains inactive/stale, we will fork your repo, fix any issues, and merge your icons ourselves.

Since GitHub tracks contributions by commits, you will still be credited. We also hope that you will help us merge this PR before the deadline comes.

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hi @kirinnee,

Are you still planning to work on this PR or should I take it over? Our commit policy has changed so I don't mind guiding you through the steps

**Comment by kirinnee** [comment]
Hi I'll be glad to continue this PR. Please LMK what i need to do

**Comment by Thomas-Boi** [comment]
Hi @kirinnee,

Thank you for responding and continuing with this PR 😃.

First, we inadvertently accepted another PR that contains [DotNet Core](https://github.com/devicons/devicon/tree/master/icons/dotnetcore). This means that your DotNet Core icon will have to be removed. However, we still have space for your Amber icon.

Here are the brief steps on how to add your Amber icon:
- Close this PR.
- Remove the dotnet core icons.
- Merge the latest changes from `develop` branch
- Follow the steps laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview). If there are any questions, please follow the links or you can leave a message in this PR.
  - Heads up: I notice that you only have an `original` icon. I think it is simple enough to be made into a font so there's no need to make a `plain` version. However, we will double check later using one of our bots so stay tuned.

Thank you for your patience, I hope that we will see your icons in here soon :)

**Comment by Thomas-Boi** [comment]
I'm going to close this PR for now. Feel free to make a new one whenever you are ready

**Pull request closed without merging**
