### PR TITLE
new icon: maya (original, original-wordmark, plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by BenSouchet**
# **New icon section**

I'm a Software engineer, I worked for VFX companies creating tools in Maya, Maya as two programming languages: MEL (proprietary), and Python 2 (Python 3 since Maya 2022). I want to use this icon with Devicon this is why I create this PR :)

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
I created the SVG (& EPS) files based on the official logo and icon versions shipped with the software:
mayaico
mayaico2

### CODE REVIEW

**Comment by BenSouchet** [comment]
@Panquesito7 okay done, I used the Python SVG as references, this is why I haven't added a new empty line at the end of the files.

**Comment by Panquesito7** [comment]
It looks like the Maya wordmark is a bit uncentered. 😅

image

Do you think you could try to center it more? Let us know if you need any help! Thanks. 😃

**Comment by BenSouchet** [comment]
@Panquesito7 You talk about the word "MAYA" ?
if yes, it's exactly like the icon I shared in the PR Autodesk put the word in small aligned right.

**Comment by Panquesito7** [comment]
> @Panquesito7 You talk about the word "MAYA" ? if yes, it's exactly like the icon I shared in the PR Autodesk put the word in small aligned right.
> 
> PS : I know it's weird design put it's exactly the logo :)

Ahh yeah! I see I see. Thanks!

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by Thomas-Boi — APPROVED** [review]
This looks phenomenal considering how complex the original version is. Good job @BenSouchet

**Pull request merged**
