### PR TITLE
new icon: gtk (original)

### PR DESCRIPTION
**Pull request by ngdream**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.gtk.org/

### CODE REVIEW

**Comment by Snailedlt** [comment]
@ngdream can you please rebase on develop, so we get rid of all of those commits? :)

**Comment by ngdream** [comment]
> @ngdream can you please rebase on develop, so we get rid of all of those commits? :)

i did it

**Comment by Snailedlt** [comment]
Then you did it incorrectly :/
There's still 41 commits, but as far as I can tell, only the last 2-3 are related to this PR

**Comment by Snailedlt** [comment]
If you create a new branch based on develop, you can cherry-pick the commits you want.

So pretty much do like this:

```sh
#checkout and update local develop branch
git checkout develop
git fetch
git reset --soft upstream/develop

#checkout new branch based on develop
git checkout -b "feature/icon/gtk"

#then cherry pick the commits you want
git cherry-pick <commit-id>
```

**Pull request closed without merging**
