### PR TITLE
new icon: tensorflow (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)

### PR DESCRIPTION
**Pull request by reevesba**
Issue #582

### CODE REVIEW

**Comment by reevesba** [comment]
Looks like a couple of the svgs were corrupted during the resize. I will make another commit shortly.

**Comment by Thomas-Boi** [comment]
Hey @reevesba,

Thank you for the icons 😃 

Unfortunately, there are a few issues that we'd need to address:
- The icons and svgs are not centered within its `viewbox`. Can you please change it so all SVG are centered?
- The `wordmark` versions of the icon are unfortunately not what we defined as wordmark. Here is what a `wordmark` version look like:
image

A possible fix would be removing the `wordmark` svgs or updating it so it contains the technology name as shown above. Note that you'll need to convert strokes to fill when working with texts since Icomoon (the icon making site) can only parse fills.

- I notice that the `original` and `plain` versions are exactly the same. In this case, you can remove one (I'd suggest the `plain` one) and remove its reference within the `devicon.json`. This will help keep the font and css file small.

Thank you again and I hope to see this icon in the repo soon.

**Comment by reevesba** [comment]
Hi @Thomas-Boi, 

Thanks for the tips. The original did have color which was the only difference. I will go ahead and remove the plain versions and update devicon.json. I will also update the wordmark versions, convert strokes to fill and center the svgs in the viewbox.

**Comment by Thomas-Boi** [comment]
Hey @reevesba ,

The icons look great! Thank you for your effort. We just need to get a feature into develop before we can merge your PR in. This should take a few more days and then, your icons will be accepted!

**Review by Thomas-Boi — APPROVED** [review]
So good news: we've decided to postpone the update for a few days. In short, we are trying to update the svgs in our repo so it's optimized and has an unique id within the whole repo. Since we will have to do this for the whole repo, we can accept your PR and update your svgs then rather than do it now.

In summary: Thank you for the icons @reevesba!

**Pull request merged**
