### PR TITLE
update icon: firebase (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Firebase Website](https://firebase.google.com/)
- [Firebase Branding](https://firebase.google.com/brand-guidelines)

## Additional Notes

The yellow color `#ffcc2e` was used for the font SVGs and is can be found on the bottom shape of the original svg.

### CODE REVIEW

**Review by weh — APPROVED** [review]
LGTM 👍

**Review by Snailedlt — COMMENTED** [review]
Another great PR! However I'm not sure that yellow is the right color choice. I feel like the middle orange color (`#ffa712`) should be chosen instead. 
Anecdotally I've found that orange is more commonly used on their website, it's also what I associate with firebase. Another good reason to pick that color imo is that it's a middle-point between the yellow and dark orange color, and it's more easily visible on white backgrounds, while also being bright enough for dark backgrounds.

Would love a 2nd and 3rd opinion on this though, which is why this is a "comment" and not a "request changes" review. @lunatic-fox @canaleal @weh what do you guys think?

**Comment by canaleal** [comment]
Honestly, I was little hesitant on choosing yellow for those exact same reasons (Hard to see, prominent on the logo but not the most common color on the website). I think the dark orange is a bit too much, but the middle orange `#ffc928` is just right.

**Comment by lunatic-fox** [comment]
> Another great PR! However I'm not sure that yellow is the right color choice. I feel like the middle orange color (`#ffa712`) should be chosen instead. Anecdotally I've found that orange is more commonly used on their website, it's also what I associate with firebase. Another good reason to pick that color imo is that it's a middle-point between the yellow (`#ffcc2e`) and dark orange (`#f6830e`) color, and it's more easily visible on white backgrounds, while also being bright enough for dark backgrounds.
> 
> Would love a 2nd and 3rd opinion on this though, which is why this is a "comment" and not a "request changes" review. @lunatic-fox @canaleal @weh what do you guys think?

I like the `Firebase Amber` which is `#ffa000`.

Here are the official colors:
Firebase Yellow: `#ffca28`
Firebase Amber: `#ffa000`
Firebase Orange: `#f57c00`

**Review by Snailedlt — CHANGES_REQUESTED** [review]
The color needs to be changed to `#ffa000`, which is Firebase Amber ([ref](https://firebase.google.com/brand-guidelines#colors))

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️
Looks Great! 💯 Thank you for another great PR! 🙇‍♂️

**Pull request merged**
