### PR TITLE
Update the `check-bot`

### PR DESCRIPTION
**Pull request by Thomas-Boi**
# **New feature section**

## Double check these details before you open a PR

- [ x ] PR does not match another non-stale PR currently opened
- [ x ] PR name matches the format *New Feature: a brief description of feature*

## This PR adds/fixes

`Check-bot`:
- Now checks for strokes => user can fix it right away without waiting for `peek-bot`
- Also checks for svg file name and ensures it matches our convention.
- Also ignores `x` and `y` in the `svg` and will not give warning for it
- Move `devicon.json` entry check from `peek-bot` to `check-bot`

`gulp-task`
- Now removes the `x` and `y` attributes of the `svg` element. This correspond with the above `check-bot` ignoring `x` and `y`

`peek-bot`:
- Remove `devicon.json` entry check

## Notes

This changes the name of the `check_svgs` workflow and updates the `post_check_svgs_comment` yaml. Thus, the workflow won't work properly until the PR is merged into `master`. I'll open this as the last thing before a release.

I tested the workflow locally on my computer and in my fork. You can test it as well by running `python ./.github/scripts/check_icon_pr.py "new icon: your-testing-icon (original, plain)" ./icons ./devicon.json` in the project's root folder. Just modify the SVGs pointed to by `your-testing-icon` (say, `react`) and check the `err_messages.txt`. Also try modifying the `devicon.json` (like removing the `aliases` or adding an invalid version `colored`) and see the error.

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
@amacado @Panquesito7 this is a big PR so let me know if you have any questions

**Review by amacado — APPROVED** [review]
Looks good to me! 😄

**Review by Panquesito7 — APPROVED** [review]
I don't know too much about this, but overall it looks good to me. Thanks! 🚀

**Comment by Thomas-Boi** [comment]
Hi @amacado, this PR is changing the Check SVG action. This is interfering with the merging process because "Check the SVGs' quality" action is not running anymore. Can you remove this requirement for the PR to be merged please?

**Pull request merged**
