### PR TITLE
new icon: traefikmesh (original, original-wordmark, plain-wordmark)

### PR DESCRIPTION
**Pull request by kilian-paquier**
## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR contributes to #923**

## Link to prove your SVG is correct and up-to-date.

https://doc.traefik.io/

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
træfik should be added as altname, and kubernetes as a tag

**Comment by Snailedlt** [comment]
Sidenote: Remember to check the boxes in your PR description, so we know what you checked and what you didn't :)

**Comment by Snailedlt** [comment]
@kilian-paquier I think this icon is pretty easy to make as a line icon too. Would you want to look into that before merge, or would you rather make a new PR for that?

**Comment by kilian-paquier** [comment]
@Snailedlt I can take a look yes

**Review by Snailedlt — APPROVED** [review]
LGTM ✔️
Thanks for contributing! 💯

**Pull request merged**
