### PR TITLE
update icon: aarch64 (original, plain, line)

### PR DESCRIPTION
**Pull request by Snailedlt**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Changes
Optimize icons, add alias to wordmark versions and add line version

### CODE REVIEW

**Review by canaleal — COMMENTED** [review]
JSON and the icon formats are good. Just wondering through but there appears to be some artifacts on the the SVGs. 

image

Haven't found an HD version of the Icon anywhere, so I guess it was some artifacts left over from an image upscaler. It does seem to be a part of the original PR though: 

- https://github.com/devicons/devicon/pull/507

If it's a non-issue, then I can approve the PR.

**Comment by Snailedlt** [comment]
@canaleal I saw that too, but assumed it was a part of the logo since it was there in the original version.
After looking online it seems like it shouldn't be there... So these icons need to be remade.
Ref: https://www.konsulko.com/home-servers-aarch64-and-you-well-me/aarch-64-logo-transp

**Comment by Snailedlt** [comment]
@canaleal The original icon was created by converting a PNG (since there were no SVG's available) in this PR: #507
I think the reason it got a bit messed up like that is because of the low resolution of the image. 
image

I redid the icon using a slightly higher resolution PNG, which I found with this [reverse image search](https://lens.google.com/search?ep=cntpubb&hl=nb-NO&re=df&s=4&p=AbrfA8r2_QZDljUN-ia2B5akKpjb07FfDk_FpyhBOUjiu2ybWLZvEOyTOKYpShA0fw2i4E8-cZBPGxeXnk3Fk7IuBFzGnIVtyh6Sn0bwPXlAepBaGghPGf3gs2QJKMljW31aA8ECzTJH1rN7QqIvOlkpPqAeID6XP3vRQvi3xjMVXAWz1q6pEcxa152n7tz9U6DAJgMyDHKX_hnrgDMu5mRhN4k8vU7Ssb1cd7t-I01ku6PN2RAqBmqHPJ9NY2J_49OVG60IQ3IrlF3gia61BkMHvTOHq6eLjFrZAWIxv_skmWBQJItcuaghjV80I6mEzSmnD0Rba58VxA6Zj9E4_KwLrMoACa7j-6XdVmjX2uxZCEmBfsHACXnq0Xyo2bgkgqznfDk6ulyTSn454t_pdVGjJPjm2GPl2jGgOZ1ix-ZNFwvfd8COTKtArLce12hAR9nMLZEUlZxA#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRFJqTlRVMU9UYzFMV00xWmpZdE5EaGtNaTA0TTJZekxUaGlPRFUyTUdZd016azNOaElmV1RoR1JrSldPSGd6VUc5WVdVUnpaM0puWDBNeFVEWjBTMnhXTlhWQ1p3PT0iXQ==):
703efef0ad1aa23d216e6071d48e1798

Here's the resulting SVG after converting it using Inkscape:
aarch64-original

It looks a bit better compared to the old one:
aarch64-original (1)



It's not perfect... especially not the text, but I don't have the skills to fix it myself, so I suggest we merge this PR and create a separate issue about fixing the path of the icons, especially the text.

**Comment by Snailedlt** [comment]
Actually I found an awesome tool to convert Raster images to PNG: https://vectorizer.ai/
After that I can changed the colors using this tool: https://svgcolor.com/

The end result is awesome imo!
aarch64-original
aarch64-plain
aarch64-line

**Review by canaleal — APPROVED** [review]
Great find! Also nice work as always.

**Comment by Snailedlt** [comment]
## How to convert bitmap/raster images (`PNG`, `JPG`, `JPEG`, ...) into SVG's
Using online tools
1. Convert raster to svg
    1. Go to https://vectorizer.ai/ and upload your raster image
    image
    1. Click on Download
    image
    1. Group paths by color, and click download to download the `.svg`. Keep everything else the same... it should look like in the screenshot below: 
    image
1. **(Optional)** Simplify the color palette
    1. Upload the downloaded `.svg` file to https://svgcolor.com
    image
    1. Get the colors from the original raster image using another tool (I recommend using the [Color Picker](https://learn.microsoft.com/en-us/windows/powertoys/color-picker) inside [PowerToys](https://github.com/microsoft/PowerToys/releases/latest) if you're on windows... then you can pick a color using the keyboard combination: <kbd>windows</kbd>+<kbd>shift</kbd>+<kbd>c</kbd>)
    1. Back on svgcolor.com, replace similar colors with the picked colors in the color picker: 
    image
1. **(Optional)** Bring the image into Inkscape or vscode to remove any extra paths, for example outlines or backgrounds that didn't exist in the original raster image

**Comment by Snailedlt** [comment]
Since this icon needs to be updated for the upcoming release, I'll merge it with only 1 approval. Please do review it even after it's merged though, so I'll know if something is wrong :)

**Pull request merged**
