### PR TITLE
fix check svg icons workflow

### LINKED ISSUE #505: Workflow "check the SVGs' quality" reports error on "devicon.svg"
When a new pull request is created, the workflow "Check the SVGs' quality" will run and check the svg's. Than this error occurs:
image

I traced this error and it found the reason for this. It's caused by `fonts/devicon.svg` - which is added on the icomoon fonts generation. I will try to fix this error.

### PR DESCRIPTION
**Pull request by amacado**
add check for directory /icons when workflow is executed (fixes #505)

### CODE REVIEW

**Comment by amacado** [comment]
@Thomas-Boi I came up with a solution for #505, but there might be a more elegant solution? I'm not very familiar with python.

**Review by Thomas-Boi — DISMISSED** [review]
Everything seems good for me.

**Review by Thomas-Boi — APPROVED** [review]
Nope, false alarm. It seems like the path is relative and not absolute as I feared. In conclusion, we are good to go.

**Comment by Panquesito7** [comment]
Why did the bot report an issue? Is it because there are no `.svg`'s being modified in this branch?

**Comment by Thomas-Boi** [comment]
> 
> 
> Why did the bot report an issue? Is it because there are no `.svg`'s being modified in this branch?

It was because there is an `.svg` file in the `/fonts` that it also checks. While the `.svg` in the `/icons` need to adhere to our standards, the one in the `/fonts` don't need to => The bot doesn't know this and just report what it finds.

**Comment by amacado** [comment]
> Why did the bot report an issue? Is it because there are no `.svg`'s being modified in this branch?

You are right! In **this** pull request the bot reported an error because there are no new/modified svg's in this branch. We could fix this. I will draft this pull request and see what I can do.

 @Thomas-Boi refers to the other bot comments on the pull requests where the bot reported an error with `devicon.svg` (as I described the problem in #505)

**Pull request merged**
