### PR TITLE
new icon: nhibernate (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)

### LINKED ISSUE #404: Icon request: NHibernate
### About the icon
NHibernate is an object-relational mapper for the .NET framework
### Links

[WebSite](https://nhibernate.info/)
[Logo](https://github.com/nhibernate/nhibernate-core/blob/master/logo/NHibernate-logo.svg)
[NuGet Package Logo](https://github.com/nhibernate/nhibernate-core/blob/master/logo/NHibernate-NuGet.png)

### PR DESCRIPTION
**Pull request by kilian-paquier**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #404**

## Link to prove your SVG is correct and up-to-date.

https://nhibernate.info/
https://github.com/nhibernate

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient, Elegant

**Comment by kilian-paquier** [comment]
Removed the generation of a font for the original svg, was a duplicate of the plain font

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Could you please fix the merge conflicts on the `devicon.json` file?
Let us know if you need any help with that! 🙂


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by kilian-paquier** [comment]
Rebase done

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thank you for your contribution! 🚀
I'll merge in the next few days if there are no objections.


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient, Elegant

**Review by Snailedlt — DISMISSED** [review]
LGTM!

**Comment by Snailedlt** [comment]
@Panquesito7 time to merge? :)

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Suggested some other tags.
If you want you can also try to make line icons for it :)

**Comment by kilian-paquier** [comment]
> Suggested some other tags. If you want you can also try to make line icons for it :)

image

Something like that ?

**Comment by Snailedlt** [comment]
Yeah, something like that :)

**Comment by kilian-paquier** [comment]
image

And like that?

**Comment by Snailedlt** [comment]
@kilian-paquier yes, but it should only have a single color. See https://github.com/devicons/devicon/wiki/SVG-Standards and https://github.com/devicons/devicon/wiki/SVG-Versions

**Comment by kilian-paquier** [comment]
Hello, yes. That was just a draft to show which parts were going to be "lined". I've made the changes.

**Review by Snailedlt — APPROVED** [review]
Very nice!
Thanks again for contributing! 💯

**Pull request merged**
