### PR TITLE
new icon: azure (original, original-wordmark, plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by ThomasMoran**
Addressing #599 

Using the new Azure logo https://azure.microsoft.com/en-gb/blog/a-fluent-new-look-for-the-azure-icon/ 

azure-logo

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Overall, the icons look good. However, I don't know why the wordmark version is having weird artifacts like that.

Can you try splitting the text into a separate `<path>` than the A? I'm not sure if it will work but I can't think of any other reason.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The icons look great. Good job, @ThomasMoran! 😄👍
Just one thing: please try to remove that on the SVG.

image

**Review by Panquesito7 — APPROVED** [review]
LGTM. Awesome work, @ThomasMoran! You did great to be your first contribution here. We hope you keep contributing! Thank you! 😄👍🎉

**Review by Thomas-Boi — APPROVED** [review]
Wonderful! You did a great job fixing the SVG. I'll merge this icon in now.

**Comment by Thomas-Boi** [comment]
This PR will now be used as part of our docs.

**Bug**: Icon version contains strange artifacts when built using Icomoon.

**Fix**: Before, the "A" logo and the word "Azure" were joined as one `<path>` object. I suggested that the contributor split them into two separate path objects: one for the "A" and one for the "Azure".

**Here is what the icon looks like before the fix:**
image

**Here is what it looks like after the fix:**
image

**Pull request merged**
