### PR TITLE
new icon: apachespark (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #583: Icon request: Apache Spark
### Links
https://spark.apache.org/

### PR DESCRIPTION
**Pull request by luizcarloscf**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #583**

## Link to prove your SVG is correct and up-to-date.

https://spark.apache.org/images/
https://spark.apache.org/

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]

**Comment by Snailedlt** [comment]
@luizcarloscf please take a look at my suggested changes when you have time :)

**Comment by Snailedlt** [comment]
@luizcarloscf bump :)

**Comment by luizcarloscf** [comment]
I kind of forgot about it, I'll go through the proposed changes this weekend

**Review by Snailedlt — COMMENTED** [review]
LGTM! ✔️ 
Thank you for your contribution! 🙇

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️ 
Thank you for your contribution! 🙇

**Pull request merged**
