### PR TITLE
new icon: biome (original, original-wordmark, plain-wordmark, line, line-wordmark)

### LINKED ISSUE #2107: [ICON REQUEST]: Biome
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Biome describes itself as a performant toolchain for web projects that serves as a fast formatter for JavaScript, TypeScript, JSX, and JSON, as well as a performant linter for JavaScript, TypeScript, and JSX. It has been in development for some time, beginning as a fork of Rome, and has grown into a large independent project that holds its own as an alternative to ESLint + Prettier.

### Links and sources

**Website**: https://biomejs.dev/
**Repository**: https://github.com/biomejs/biome

**[Official Logo SVG](https://github.com/biomejs/biome/blob/main/website/src/assets/svg/logomark.svg)**:
Official Logo SVG

**[Official Wordmark SVG](https://github.com/biomejs/biome/blob/main/website/src/assets/svg/logo-light-transparent.svg)**:
Official Wordmark SVG

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by angelajfisher**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #2107**

## Link to prove your SVG is correct and up-to-date.
Blog post introducing new logo: https://biomejs.dev/blog/roadmap-2024/#new-logo-and-homepage

**[Official Logo SVG](https://github.com/biomejs/biome/blob/main/website/src/assets/svg/logomark.svg)**:
Official Logo SVG

**[Official Wordmark SVG](https://github.com/biomejs/biome/blob/main/website/src/assets/svg/logo-light-transparent.svg)**:
Official Wordmark SVG

### CODE REVIEW

**Review by canaleal — CHANGES_REQUESTED** [review]
Thank you for the contribution and excellent work updating the json! I've marked down some changes. 


To maintain a cohesive look, it would be good to update the `line-wordmark` and `line wordmark` fills with the `#60a5fa` color used in the original.svg and plain-wordmark.svg. 

The strokes in the line SVGs have to be updated to paths. In inkscape this an can be done by selecting all paths and then using the strokes > paths option. 

image

The line-wordmark, plain-wordmark, and original-wordmark have to be scaled to reach the edges of the viewbox. 
image

**Comment by angelajfisher** [comment]
Hi @canaleal, thank you so much for reviewing my PR and for the detailed feedback! My apologies for the oversights. I've pushed changes to hopefully remedy all of the problem areas, but I'm happy to iterate further if needed.

**Review by canaleal — APPROVED** [review]
Excellent work!
Hope you don't mind but I optimized the SVGs to verify how they look on Icomoon.
Thankfully all icons look good and there are no artifacts.
image

Also, we use the following [tutorial](https://github.com/devicons/devicon/issues/1279#issuecomment-1195433256) to optimize the SVGs.

**Review by weh — APPROVED** [review]
Looks good to me :+1:

**Comment by angelajfisher** [comment]
Awesome, I appreciate the help and guidance! Thank you so much for allowing me to contribute!

**Pull request merged**
