### PR TITLE
new icon: LabVIEW (original, plain, original-wordmark, plain-wordmark)

### PR DESCRIPTION
**Pull request by mjlabe**
LabVIEW icon from PR #136

labview-original-wordmark
labview-original
labview-plain-wordmark
labview-plain

### CODE REVIEW

**Comment by amacado** [comment]
Hello @mjlabe thanks for this contribution! I tried to google for LabView logo/icon but could not find the design you provided. Is this your own creation/adaption?

**Comment by mjlabe** [comment]
Sort of. I've used it for years and the logo changes a bit over time. It started as 

https://blog.digilentinc.com/wp-content/uploads/2017/02/labview_logo-e1486411393153.png

And moved to this

https://labviewwiki.org/w/images/thumb/2/2d/LV2019.png/256px-LV2019.png

But my plain is this

https://yt3.ggpht.com/-T6wZgUnViz0/AAAAAAAAAAI/AAAAAAAAAAA/4jmqj1FlGY4/s900-c-k-no-mo-rj-c0xffffff/photo.jpg

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hello there,

We notice that this PR has been inactive for awhile now. It would be a waste of your time and effort if we just close this PR and throw away the SVGs in here. Thus, 1 month from now, if this PR remains inactive/stale, we will fork your repo, fix any issues, and merge your icons ourselves.

Since GitHub tracks contributions by commits, you will still be credited. We also hope that you will help us merge this PR before the deadline comes.

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hi @mjlabe,

I'm working on merging your PR to accept your icon. However, it seems like your branch is a bit out of date. It'd be much appreciated if you can bring the branch up to date with develop and re-push.

After a week, if the branch hasn't been updated I'll make a new PR cherry-picking your commit. This is to ensure you are still the author of the commit and get proper credits. You can also just give me permission to do it this way now.

It'd be quicker if you update the branch yourself though but whichever works 👍

**Comment by Thomas-Boi** [comment]
I just changed the colors in your icons so it matches the ones found in the last 5 years. You can see the icon [here](https://labviewwiki.org/wiki/LabVIEW_Versions). You can view the new PR at #626

**Pull request closed without merging**
