### PR TITLE
new icon: Github Actions (original,plain)

### LINKED ISSUE #1423: [ICON REQUEST]: GitHub Actions
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. 

#### Website
https://github.com/features/actions

#### Official Logo
https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yeyeto2788**
## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1423 **

## Link to prove your SVG is correct and up-to-date.
githubactions

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Hi @yeyeto2788 👋 
Thank you very much for your contribution! 🚀 

Sadly I can see that this PR is based on the `master` branch, and not the `develop` branch. Would you mind rebasing/merging on the `develop` branch, or starting a new PR based on the `develop` branch please?

I recommend you also check out the [Overview on Submitting Icons](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons) wiki post for a wuick refresher on how we do things :)

**Comment by yeyeto2788** [comment]
Hey there! Sorry for the late reply on this one. I tried to rebase from develop and I get this error while trying to push to my fork
image

I had to enable the `workflow` option on the token I had but it would be great to add it into the document you linked here in regards to how to add new icons.

**Comment by Snailedlt** [comment]
> Hey there! Sorry for the late reply on this one. I tried to rebase from develop and I get this error while trying to push to my fork image
> 
> I had to enable the `workflow` option on the token I had but it would be great to add it into the document you linked here in regards to how to add new icons.

Sorry I'm not following... What token are you talking about?

**Comment by yeyeto2788** [comment]
Hey there! 

This error was shown when trying to submit code to my fork and since there is a defined workflow that gets executed on each commit or at least that what I understood from the `.github/workflows/post_check_icon_pr_comment.yaml` file. So one of the tasks/jobs need the API token in order to execute the workflow.

The API tokenI had enabled didn't have the option for workflow so I needed to enabled it.

I'm telling you guys this because maybe someone might face the same issue.

**Comment by Snailedlt** [comment]
Ohh I see. Hmm, sounds like a bug to me. You shouldn't have to change anything inside .github in order to run the workflows, so I'm guessing it might be something similar to this bug: https://github.com/devicons/devicon/issues/1099

**Comment by yeyeto2788** [comment]
I don't really think it is deeply related to that issue but more on the users' API token configuration. So for that I followed the steps as shown in here https://stackoverflow.com/a/64080046 and everything just worked.

In my case I had already a token generated and some other users might need to create them.

**Comment by Snailedlt** [comment]
@yeyeto2788 Ahh, okey. 


From the SO link you sent: 
> Background: third-party tools with GitHub integrations like IntelliJ, Visual Studio Code, Github Desktop, etc use tokens to connect to your GitHub account so they can pull/push, etc on your behalf. In the case of IntelliJ, their instructions only say to include the repo, the gist, and the read:org scopes. But you need the workflow scope to modify GitHub Actions.

Seems like a problem with the tools you used and not devicons itself. If you use a normal workflow with for example vscode and git, you should have no issues. 

Let me know if this is wrong though, and if you still think it's something that needs to be documented or fixed in another way

**Pull request closed without merging**
