### PR TITLE
Add White solidity logo

### PR DESCRIPTION
**Pull request by Juiiceee**
I have juste add white solidity logo

### CODE REVIEW

**Comment by canaleal** [comment]
Hey @Juiiceee,

Unfortunately, Devicons currently doesn't support the SVG versions you mentioned. As mentioned in the wiki, we only support the following SVG types:

- Original
- Plain
- Line

**Comment by Juiiceee** [comment]
> Hey @Juiiceee,
> 
> Unfortunately, Devicons currently doesn't support the SVG versions you mentioned. As mentioned in the wiki, we only support the following SVG types:
> 
> * Original
> * Plain
> * Line

Zut :(

**Comment by Snailedlt** [comment]
@Juiiceee if you just want the plain version in white color you can use the devapix to change get the logo in any color you want :)
https://devapix.vercel.app/docs/pages/gettingicons/color

**Comment by Snailedlt** [comment]
Here's the white version from the API: https://devapix.vercel.app/api?solidity&color=white

**Pull request closed without merging**
