### PR TITLE
new icon: rect (original, plain)

### PR DESCRIPTION
**Pull request by RedCubeDev-ByteSpace**
# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
[ReCT Website](https://rect.ml/)
[ReCT-Go-Compiler](https://github.com/ReCT-Lang/ReCT-Go-Compiler)
[Original ReCT C# Compiler](https://github.com/RedCubeDev-ByteSpace/ReCT)

## Notes
Hi there 👋
ReCT is a small programming language maintained by me and a few others and one of our Discord members suggested adding our language here! The icons are based on the original Logo but were specifically created for this so I couldnt link the logo directly!

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Hi @RedCubeDev-ByteSpace,

The quality of the icon is good. However, the links you gave us show this version of the icon more often:
image

I think it's better if you submit this version instead.

**Comment by RedCubeDev-ByteSpace** [comment]
Oh alright no problem!
I thought id go for something thats better readable at a smaller size haha

**Comment by Thomas-Boi** [comment]
> Oh alright no problem! I thought id go for something thats better readable at a smaller size haha

@RedCubeDev-ByteSpace that's fair. However, we try and use the official icon wherever possible. It reduces chance for mistakes or legal issues.

**Comment by RedCubeDev-ByteSpace** [comment]
Alrighty ive changed the icon from the simplified variant to the full one ^^

**Review by Thomas-Boi — APPROVED** [review]
Alrighty, this looks good @RedCubeDev-ByteSpace! Thank you for your work 😄

**Pull request merged**
