### PR TITLE
new icon: liquibase (original, original-wordmark)

### PR DESCRIPTION
**Pull request by kilian-paquier**
### Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format new icon: Icon name (versions separated by comma). More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the develop branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the devicon.json file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

### Link to prove your SVG is correct and up-to-date.

https://www.liquibase.org/brand (wordmark)
https://www.liquibase.org/wp-content/themes/liquibase/assets/img/cta-icon-org.svg (none-wordmark)

PS : Converted the PNG image into a SVG. I'm also not sure about the aliases, the original svg can be used for the plains version, do i need to add something to the devicon.json ?

### CODE REVIEW

**Review by amacado — DISMISSED** [review]
@kilian-paquier would you consider adding the new `"altnames": []` attribute for liquidbase? https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository

thank you for the contribution!

**Comment by kilian-paquier** [comment]
> @kilian-paquier would you consider adding the new `"altnames": []` attribute for liquidbase? https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository
> 
> 
> 
> thank you for the contribution!

Hello,

Will do today ! Do I need to add aliases as the original svg is also the plain svg ?

**Comment by amacado** [comment]
yes, you could add an alias for it following this guide https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60#aliases-and-aliasobj

**Comment by kilian-paquier** [comment]
Hello @amacado,

Thanks for reviewing the PR. The requested change is pushed.

**Review by amacado — APPROVED** [review]

**Pull request merged**
