### PR TITLE
new icon: puppeteer (original, plain)

### LINKED ISSUE #1795: [ICON REQUEST]: Puppeteer Icon
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Puppeteer is a headless browser automation tool with a powerful API, enabling developers to automate browser tasks, interact with web pages, and extract data in a programmatic manner.

### Links and sources

Puppeteer Site
https://pptr.dev

SVG Logo I found
https://www.vectorlogo.zone/logos/pptrdev/pptrdev-official.svg

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Gautam25Raj**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1795**

## Link to prove your SVG is correct and up-to-date.

https://pptr.dev/

### CODE REVIEW

**Comment by Gautam25Raj** [comment]
I have 2 icons for plain-wordmark. Let me know which looks better.

  puppeteer-plain-wordmark

  puppeteer-plain-wordmark-2

**Comment by lunatic-fox** [comment]
> I have 2 icons for plain-wordmark. Let me know which looks better.
> 
> puppeteer-plain-wordmark puppeteer-plain-wordmark-2

Another option:

**Comment by Panquesito7** [comment]
I prefer the 2nd option. It's not fully black nor transparent.

**Comment by Gautam25Raj** [comment]
> I prefer the 2nd option. It's not fully black nor transparent.

Okay, lets move forward with the 2nd option. Its already been uploaded.

**Review by lunatic-fox — COMMENTED** [review]
Seems great! 👍🏼

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
