### PR TITLE
Update `package.json` for the new release

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Update `package.json` for the new release.

### CODE REVIEW

**Review by amacado — APPROVED** [review]
Are we done with all new Icons?

**Comment by Panquesito7** [comment]
> Are we done with all new Icons?

Yeah, I think so. I was planning to add more, but I think it should be done for another release. 🙂

**Comment by Thomas-Boi** [comment]
@amacado I believe one of our contributor (maltejur) was asking for another release because they need some of the new icons in the npm package.

Also @amacado, is there anything else that we need to do for a new release. @Panquesito7  and I were talking about this and so far, the steps are:
- Update `package.json`
- Run the npm release workflow
- Open a PR into `master`

Is there anything that we're missing?

**Comment by Thomas-Boi** [comment]
Also, @Panquesito7 did you use the command to change the version? The one in the PR on the NPM release

**Comment by Panquesito7** [comment]
> use the command to change the version

No, I changed the version in `package.json` manually.

**Comment by amacado** [comment]
I will write a "how to publish" in a few hours.

**Comment by Thomas-Boi** [comment]
> I will write a "how to publish" in a few hours.

Sweet, thank you 😄. You can also message us on the Discord server as well. I've been planning to make a Google Docs or at least a `contributor-readme` for a while now. It'll be great if we can aggregate them in one place.

**Comment by Thomas-Boi** [comment]
> > use the command to change the version
> 
> No, I changed the version in `package.json` manually.

I think we should use the command. @amacado said in his PR that we also need to update the `package-lock.json`. I think we should do so just to be safe.

**Comment by Panquesito7** [comment]
What is the command? I'm not so sure what command you're talking about. 😅

**Review by amacado — CHANGES_REQUESTED** [review]
I will approve it once the how to is ready. Be prepared ;-)

**Comment by Thomas-Boi** [comment]
@Panquesito7 I was referring to the one in this [PR](https://github.com/devicons/devicon/pull/497)

**Comment by Thomas-Boi** [comment]
I'll close this branch for now. I think we can let @amacado handle things for this release. Perhaps we can work together somehow? There's a lot of things needed to be done to create a new release.

**Pull request closed without merging**
