### PR TITLE
new icon: gazebo (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #1600: [ICON REQUEST]: Gazebo
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Gazebo is an open-source 3D robotics simulator.

### Links and sources

Project home page: https://gazebosim.org/home
Icons: https://gazebosim.org/media

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luizcarloscf**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1600**

## Link to prove your SVG is correct and up-to-date.

https://gazebosim.org/home
https://gazebosim.org/media

### CODE REVIEW

**Comment by luizcarloscf** [comment]
Sorry, I don't know why I typed "gazebo vault". It was supposed to be just "gazebo" in the last commit. And did I do something wrong that the checks don't run?

**Comment by lunatic-fox** [comment]
> Sorry, I don't know why I typed "gazebo vault". It was supposed to be just "gazebo" in the last commit. And did I do something wrong that the checks don't run?

No problem! 🙂
The check failed, because the job (program) was trying to find icons that start with "gazebo vault", but since you fixed that I reran the job and they're ok.

**Review by lunatic-fox — DISMISSED** [review]
Approved! ✔
Thank you for this great contribution! 🚀

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Whoops, I forgot to submit my review. Looks good, just want you to add one more tag :)

**Review by Snailedlt — APPROVED** [review]
Excellent PR once again! 💯 
Please consider applying for the maintainer role if you wanna help review PRs and help decide where devicons goes next!
If you're interested you can apply here: https://github.com/devicons/devicon/discussions/1436

**Pull request merged**
