### PR TITLE
new icon: Pulumi (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #1864: [ICON REQUEST]: pulumi
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

development tool -> infrastructure as code

### Links and sources

Official website: https://www.pulumi.com
Official brand / logo SVG files and colors : https://www.pulumi.com/brand/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1864**

## Link to prove your SVG is correct and up-to-date.

Official Site: https://www.pulumi.com/brand/
Github: https://github.com/pulumi/pulumi

I used Pulumi base yellow (#f6bf29) for plain and plain-wordmark.  

I was working on this a while back. Only a few minutes ago, another pull request (#1881) was created but it does not include wordmark or plains. We could merge both requests.

### CODE REVIEW

**Review by desteves — COMMENTED** [review]
LGTM! TY for putting this together <3

**Comment by weh** [comment]
I think the `plain` and `plain-wordmark` files need to have one unified path see [SVG-Standards](https://github.com/devicons/devicon/wiki/SVG-Standards)

**Comment by canaleal** [comment]
💀 @weh You're right. Will get on it right away and fix the problem.

**Review by Snailedlt — APPROVED** [review]
Great work!
Thank you for your contribution! 💯

**Review by ConX — APPROVED** [review]
LGTM! Thanks @canaleal!

**Pull request merged**
