### PR TITLE
new icon: Jupyter (original, plain)

### LINKED ISSUE #295: Icon request: Jupyter
### About the icon
Jupyter is a popular tool to write python notebooks, with its own file format based on JSON.
In an app offering to download both plain Python code and notebook, I would use the two relative icons to choose.
### Links
https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
### Preview

### PR DESCRIPTION
**Pull request by Panquesito7**
Closes #295.

I added an icon for the [Jupyter Project](https://jupyter.org/) language.
I took the icon from [Wikipedia](https://en.wikipedia.org/wiki/Project_Jupyter). I resized it using the [`resize-image`](https://www.iloveimg.com/resize-image/resize-svg) tool. 🙂

This is how it looks (both the original and plain versions):

Jupyter Notebook icon

If I missed up anything please let me know. Thank you.

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
Bases on our [CONTRIBUTING.md](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#versions-and-naming-conventions) the `plain` version should only contain one color :)
>plain: a one-color version of the original logo

The `original` version looking good and `devicon.json` is also fine! :) Thanks @Panquesito7

**Comment by amacado** [comment]
@Panquesito7 side note: Please checkout the `development` branch and not the `master` branch, when adding a new icon :)

**Comment by amacado** [comment]
Please checkout the `development` branch and create the pull request against the `development` branch. I will close this pull request, since it messes up all our automated tasks ;-) Sorry!
Please follow our [guidelines](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#overview-on-submitting-icons):
> 4. Create a separated pull request (PR) towards the develop branch for each Icon.

Thanks for improving this project! :)

**Comment by Panquesito7** [comment]
Oh, sorry, my bad. I will re-make the PR. Thank you. 🙂

**Comment by Panquesito7** [comment]
#501.

**Pull request closed without merging**
