### PR TITLE
add feature:icon and enhancement labels automatically

### LINKED ISSUE #1399: [FEATURE REQUEST] Add the appropriate labels automatically
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

It would be awesome if a GitHub Actions workflow detected if a new directory has been made under the `icons` folder, and added the appropriate labels. The `bot:peek` label could be added too if it matches all the requirements and standards (it could take a bit long time to code, though).

What do you think about this? 🙂

### Possible Solution

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Snailedlt**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

add ![][~feature:icon] and ![][~enhancement] labels to pull_request_template.md, so that the labels are added automatically when users copy the link

**This PR closes #1399**

## Notes

I think this needs to be merged to master before it takes effect

[~feature:icon]: https://img.shields.io/badge/-feature:icon-6cc43c.svg
[~enhancement]: https://img.shields.io/badge/-enhancement-84b6eb.svg

### CODE REVIEW

**Review by lunatic-fox — APPROVED** [review]
Approved! ✔

Unfortunately yes, as you said, it'll need to be merged to `master` before it takes effect.

I've made a test and the template works only with `default` branches. Then, on the test, I've changed `develop` as the default branch and it worked. 🤔

**Comment by lunatic-fox** [comment]
> @lunatic-fox What do you mean by `the template works only with default branches.`?

Whoops, I mean it in singular: "default branch".

Take a look at `main` branch, is labeled with `default`. So the template will be based on info from `main`.
If `default` label is on `develop`, for instance, the template will be based on the info from `develop`.
It's the "Switch default branch" action. However, I made it just for test in a separated repo.

**Comment by Snailedlt** [comment]
aha! I didn't know that :( What a bummer! Well, not much we can do about it though I guess :/ 

Well, maybe we can consider making `develop` the default branch instead I guess? That will also make the repo look more active to outside contributors, since `develop` is updated much more often than `master`.

Just have to look at what the other consequences of changing the default branch would be. We can make a discussion about it if you also think it should be considered :)

**Comment by lunatic-fox** [comment]
Nah, that's ok! I also discovered it now, because I was testing. 🙂

I got the same idea of using `develop` as the default branch, for the same reasons, but I think better take a look at the consequences even before open a discussion.

I'll bookmark this PR in my notifications. 📑

**Comment by Snailedlt** [comment]
Hmm, weird. It works on non-default branches for me.

See this example: https://github.com/devicons/devicon/compare/develop...Snailedlt:devicon:dup/check_if_pr_base_is_develop_on_icon_prs?quick_pull=1&template=new_icon.md&labels=feature:icon
image


Could you please double check if it works for you @lunatic-fox ?

**Comment by lunatic-fox** [comment]
Hi @Snailedlt!

Yeah it'll work this way on any branch, but the issue that we're talking about before was related to when someone create a pull request the placeholder comment will be based on `master` branch, so it will not have the `&labels=feature:icon` suffix, even if this current PR is merged to `develop` branch.

To be clear, when this PR is merged to `develop` it'll not affect the placeholder link when we create a PR, but when a new version is released and eventually merged to `main` it will show the proper placeholder link.

**How it is**


**How it should be**

**Comment by Snailedlt** [comment]
@lunatic-fox Ahh yes, so then it's as I initially expected. Then there should be no issue merging it to develop now right? Also means that we don't need to change the default branch to master imo :)

**Comment by lunatic-fox** [comment]
Yes, it's fine to merge to `develop`.

What I didn't test yet, and will not have much time to do now, was about the consequences to turning `develop` into the default branch, so the best by now it's leave the way it is, in my opinion. And merge your pull request to `develop`. Maybe we can work more on that idea in the future.

**Comment by Snailedlt** [comment]
> Maybe we can work more on that idea in the future.

Definitely!

> Yes, it's fine to merge to develop.

I'll merge then 👍

**Pull request merged**
