### PR TITLE
new icon: StencilJS (original, original-wordmark)

### LINKED ISSUE #866: Icon request: Stencil
### About the icon

Stencil is a toolchain for building Web Components

### Links and sources

[Homepage](https://stenciljs.com/) (Icon is inlined as SVG)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gitChaoslord**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes #866**

## Link to prove your SVG is correct and up-to-date.

The SVGs can be found [here](https://ionic.io/about/brand) by downloading the "full press kit" at the bottom of page.

I've manipulated the downloaded SVGs using the following tools
- Resizing : https://mediamodifier.com/svg-editor
- Cleanup : https://jakearchibald.github.io/svgomg/

### CODE REVIEW

**Review by canaleal — CHANGES_REQUESTED** [review]
Hey @gitChaoslord, great job! 👍

Just a couple of things to note:

1. The names "stencil-original colored" and "wordmark colored" aren't valid SVG versions. Check the [wiki](https://github.com/devicons/devicon/wiki/SVG-Versions) for a list of valid names.
 2. Make sure the SVGs adhere to the [SVG Standards](https://github.com/devicons/devicon/wiki/SVG-Standards).

It seems the official logo is the black version, so use that as the basis for "original" and "original-wordmark.svg".

**Comment by gitChaoslord** [comment]
Hello @canaleal, thank you!

I've made some adjustments based on your input.

- Removed the "colored" word from the icon names
- I've decided to name the "black" logo as `plain` and the "white" as `original`, ( My reason was the white also had an opacity attribute on one element )
- Made sure the contents are centered 
- Removed all padding on the X axis ( Y axis has some padding left to prevent distortion )

**Review by canaleal — CHANGES_REQUESTED** [review]
Excellent work 👍 Everything is almost ready. 

Just 2 more changes:

The `plain` and `plain-wordmark` svgs need to have only 1 path. You can use the unify feature in inkscape to do this. 

Great work using SVGOMG! For the final step, do the same but turn on all the feature options except:
- Remove xmlns
- Round/rewrite number lists
- Replace duplicate elements with lists

After optimizing, ensure that the svg code is one line long and includes a single empty line at the end.

**Comment by gitChaoslord** [comment]
Hello again @canaleal

I've performed the requested changes as per your instructions
- Corrected the color in `devicons.json`
- Removed `original` & `original-wordmark` from the font version
- Unified the `plain` & `plain-workmark` paths into a single one
- Formatted file contents to be in the first line and added a second empty line

**Review by canaleal — APPROVED** [review]
Perfect work!🚀 

Looks good on icomoon:
image

**Review by canaleal — APPROVED** [review]
Perfect work!🚀 

Made 2 changes: 
- Updated file name workmark to wordmark on the original svg.
- Removed the fill="none" from all SVGs. 

Looks good on icomoon:
image

**Pull request merged**
