### PR TITLE
new icon: rider (original, plain-wordmark)

### LINKED ISSUE #1071: Icon request: JetBrains Rider
### About the icon

JetBrains Rider is a cross-platform .NET IDE used by many .NET develops in favor of Visual Studio.

### Links and sources

https://www.jetbrains.com/rider/
https://www.jetbrains.com/company/brand/#logos-and-icons-product-logos

### Additional information

Other JetBrains IDEs like PHPStorm or PyCharm already made it into this repository so this would be a welcome addition.

### PR DESCRIPTION
**Pull request by thehedgefrog**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

This PR closes #1071

## Link to prove your SVG is correct and up-to-date.
[Rider product site](https://www.jetbrains.com/rider/)

### CODE REVIEW

**Comment by thehedgefrog** [comment]
I feel there might be an issue with the plain-wordmark file, while looking at it with the transparency grid I had not noticed the white text is a while fill, not transparent.  If need be, close this PR and I will resubmit the wordmark as original-wordmark in a new PR.

**Review by amacado — CHANGES_REQUESTED** [review]
There's a problem with the transparency in the icon:
image

**Comment by thehedgefrog** [comment]
> 

Should be good to go now.

**Review by amacado — CHANGES_REQUESTED** [review]
Icons looking good so far, but we require a `original` or `plain` version as statet in our requirements https://github.com/devicons/devicon/wiki/SVG-Versions. The wordmark version for the font is not enough so satisfy this requiredment. Maybe you could create a `plain` version?

**Comment by thehedgefrog** [comment]
> Icons looking good so far, but we require a `original` or `plain` version as statet in our requirements https://github.com/devicons/devicon/wiki/SVG-Versions. The wordmark version for the font is not enough so satisfy this requiredment. Maybe you could create a `plain` version?

Is the `original` version in my first commit not acceptable?

**Comment by amacado** [comment]
Sorry. My answer was incomplete: We need a `original` or `plain` version which can be made into a font. Since the current `original` is not suitable for a font we need a `plain` version

**Comment by thehedgefrog** [comment]
> Sorry. My answer was incomplete: We need a `original` or `plain` version which can be made into a font. Since the current `original` is not suitable for a font we need a `plain` version

Got it, thanks for clarifying

**Review by amacado — APPROVED** [review]

**Pull request merged**
