### PR TITLE
New Feature: Upgrade Peekbot

### PR DESCRIPTION
**Pull request by Thomas-Boi**
# **New feature section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *New Feature: a brief description of feature*

## This PR adds/fixes

The PR adds:
- Changing logging for strokes detected while being peeked. Eventually, this will be moved over to check-bot. 
- Set 8080 as the first port to try to open when making a WebDriver.
- Add retrying code to WebDriver creation. Now, the script will retry making a WebDriver 5 times before actually quitting. 
- Change the `upload-artifact` action to an earlier version so `peek-bot` work properly. When the fix for #951 is available, we will use that new version.

## Notes

Regarding the "No connection could be made" error, see #964 for more details. Also, see #965 to see the testing result of the new workflow. After I fixed some minor errors, the script works fine. There was no error opening up port 8080 as far as I can see.

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Not exactly sure what this code does, but looking perfect to me! 🚀 I removed the label and added it again, and it's working 🎉 Thanks Thomas, for your hard work and dedication! 😄👍

**Comment by Thomas-Boi** [comment]
Don't merge this yet. I'm adding an extra peek bot upgrade to it.

**Comment by Panquesito7** [comment]
I converted this to a draft PR. You can click on "Ready for review" when it's ready. 🙂

**Comment by Thomas-Boi** [comment]
Just got the feature working. Basically, `peek-bot` can now change the color of the icon to match the one provided in the `devicon.json`. This allows user to see how good the icon looks.

The only issue is for this to work, we have to merge the branch into `master`. This is only for the `color` checking though. The `upload-artifact` fix and the `no connection` fix is in. I think we can accept the currently opened PRs and make a new release.

**Comment by Thomas-Boi** [comment]
You can see the colored icons by checking the artifact created by the actions (linked to this comment)
[screenshots.zip](https://github.com/devicons/devicon/files/7730156/screenshots.zip)

**Review by Panquesito7 — APPROVED** [review]
Great work on the new feature and fixing, Thomas! 🚀 Yeah, we have to merge this to `master` as it won't work if we merge it to `develop` 😅 or make a new release so this applies then we can do the branch renaming as discussed in #967.

**Review by EthanDevelops — APPROVED** [review]
LGTM!

**Comment by Panquesito7** [comment]
Ping, @amacado.

**Comment by Thomas-Boi** [comment]
I'll just merge this in. I'm pretty confident in the script and 2 ppl have check it out.

**Pull request merged**
