### PR TITLE
new icon: vite (original, original-wordmark)

### PR DESCRIPTION
**Pull request by kilianpaquier**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

Reworking this PR : https://github.com/devicons/devicon/pull/1251

## Link to prove your SVG is correct and up-to-date.

https://www.vite.org/

### CODE REVIEW

**Review by Snailedlt — APPROVED** [review]
Thanks for picking up this PR, this is a great addition to the project 🚀 

LGTM ✔️

**Review by lunatic-fox — APPROVED** [review]
Made some changes.

Approved! ✔
Thank you for this contribution! 🚀

**Review by Snailedlt — APPROVED** [review]

**Comment by Snailedlt** [comment]
@lunatic-fox Could you please share a guide on how to remove those bug lines that show up in the icomoon preview? :)

**Comment by lunatic-fox** [comment]
> @lunatic-fox Could you please share a guide on how to remove those bug lines that show up in the icomoon preview? :)

I want to, but it depends of the icon.
However there is some kind of pattern, so let's take a look.

**Some tips of how to proceed when this bug happens**
- Try to identify where the bug line begins.
- See if there is any unnecessary node like:
  - A curve node between some line segment.
  - A node that is not preserving the shape of a curve segment.
- See if there is a line segment made by two curve nodes.
- Once identified you can:
  - Remove those unnecessary nodes, taking care to preserve the shape.
  - Or rebuild the shape.

I seriously wish to detail it quite more, but I hope those tips make this issue at least a little bit clear.

**Pull request merged**
