### PR TITLE
new icon: faunadb (original, original-wordmark, line, line-wordmark)

### LINKED ISSUE #1262: [ICON REQUEST]: FaunaDB
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Fauna is a database that is used wildly these days and I have heard a lot about it and how it uses a great new way of saving data. But I was confused when I didn't find it on Devicon at all.

### Links and sources

- [about](https://fauna.com/about)
I didn't find a good equality picture or SVG of their icon.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kilian-paquier**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1262, #769**

## Link to prove your SVG is correct and up-to-date.

https://fauna.com/about
https://images.ctfassets.net/po4qc9xpmpuh/7itYmeRxmVGIXwwGWHrQU3/42f3e7fa7d39fab5b6222f6199f0203c/Fauna_Logo.svg

### CODE REVIEW

**Review by Snailedlt — DISMISSED** [review]
LGTM! :heavy_check_mark: 
Thanks for your contribution! :rocket:

**Review by Snailedlt — COMMENTED** [review]
@kilian-paquier merge conflicts need to be solved

**Review by Snailedlt — APPROVED** [review]
LGTM! :heavy_check_mark:

**Review by Panquesito7 — APPROVED** [review]
Awesome! Thanks for contributing. 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Pull request merged**
