### PR TITLE
new icon: blazor (original, plain, line)

### LINKED ISSUE #619: Icon request: Blazor
### About the icon
Blazor lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries.
### Links
[Blazor Homepage](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)
### Preview
BrandBlazor_nohalo_1000x

### PR DESCRIPTION
**Pull request by weh**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes**
closes #619 

## Link to prove your SVG is correct and up-to-date.

https://github.com/dotnet-foundation/swag/blob/4f2805b5f56c10584a74055b9c1c688572ada023/blazor/Blazor_nohalo_16x.svg

### CODE REVIEW

**Review by canaleal — APPROVED** [review]
Devicon.json and SVG looks good. Nice use of the alias for plain by the way. Tried to find an official wordmark, but it seems as though non exist based on this comment.
- https://github.com/dotnet/aspnetcore/issues/26522

Overall, another great contribution!

**Comment by weh** [comment]
thx @canaleal i updated the PR with the official SVG

**Review by Snailedlt — APPROVED** [review]
Looks good ✅ 
Thank you for another awesome contribution! You're on fire this month!

No complaints really, but I wanna challenge you a bit @weh. 
Would you be willing to create a plain version also for this icon?
Tutorial can be found here: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

**Review by lunatic-fox — COMMENTED** [review]
Great contribution!
Here's a suggestion of `line` version:

**Comment by weh** [comment]
i added the line version (thank you @lunatic-fox) and rebased the branch to current develop.

**Review by Snailedlt — APPROVED** [review]

**Pull request merged**
