### PR TITLE
new icon: archlinux (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #180: Icon Request: Arch Linux
Could you consider adding these:     

 1. [**ArchLinux-Dark**](https://sources.archlinux.org/other/artwork/archlinux-logo-dark-scalable.svg)
archlinux-logo-dark-90dpi    
`https://sources.archlinux.org/other/artwork/archlinux-logo-dark-scalable.svg`     
    
 2. [**ArchLinux-Black**](https://sources.archlinux.org/other/artwork/archlinux-logo-black-scalable.svg)
archlinux-logo-black-90dpi
`https://sources.archlinux.org/other/artwork/archlinux-logo-black-scalable.svg`

### PR DESCRIPTION
**Pull request by jusuchin85**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #180**

## Link to prove your SVG is correct and up-to-date.
https://archlinux.org/art/

### CODE REVIEW

**Comment by jusuchin85** [comment]
This should fix it! 🤞

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Comment by jwaxy** [comment]
When will this be merged to the main branch?

**Comment by weh** [comment]
i think this PR closes  #1376

**Pull request merged**
