### PR TITLE
Added some new icons (Bash, Firebase, Flask, Google-Cloud, Kubernetes, Objective-C, Pandas, Rocksdb, SQLAlchemy, SQL-Server, uWSGI)

### PR DESCRIPTION
**Pull request by ReallyLiri**
Added icons for the following:

- Bash
- Firebase
- Flask
- Google-Cloud
- Kubernetes
- Objective-C
- Pandas
- Rocksdb
- SQLAlchemy
- SQL-Server
- uWSGI

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by jonalxh** [comment]
Hi, This icons haven't been merged yet?

**Comment by ReallyLiri** [comment]
@jonalxh unfortunately I don't have time to conform to the pull request requirements beyond making this one. If anyone wants to pick it up, you're most welcome to.

**Comment by Thomas-Boi** [comment]
Hello all,

The icons in this PR has been added by various new PRs. Props to @ReallyLiri for creating the SVGs and @EnisMulic for refactoring it and submitting the new PR.

I'll now close this PR since everything has been added.

**Pull request closed without merging**
