### PR TITLE
update icon: unity (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)

### PR DESCRIPTION
**Pull request by Snailedlt**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

fixes issues with #1977

## Link to prove your SVG is correct and up-to-date.

`line-wordmark` version was recreated using the `made-with-unity` logo: https://brandfolder.com/s/3v2rb9wqbr9sjbh5gqmmcq
all other versions are modifications of the existing versions in the develop branch.

### CODE REVIEW

**Comment by Snailedlt** [comment]
Previews:
image
image
image
image
image

**Review by lunatic-fox — APPROVED** [review]
Great one! 💯
Made a tiny adjustment on each icon by removing some unnecessary whitespace characters. 🔧 
Thank you for this contribution! 🚀

**Review by mahmudunnabikajal — APPROVED** [review]
Icon looks good!

**Review by canaleal — APPROVED** [review]
Nice. All is good.

**Pull request merged**
