### PR TITLE
new icon: plotly (original, original-wordmark)

### LINKED ISSUE #1131: [ICON REQUEST]: plotly
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

The front end for ML and data science models

### Links and sources

* [website](https://plotly.com/)
* [github](https://github.com/plotly)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luizcarloscf**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1131**

## Link to prove your SVG is correct and up-to-date.

https://plotly.com/

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
Hi! We appreciate every contribution. I'm not convinced yet, that plotly match our requirements. We'll discuss this in https://github.com/devicons/devicon/issues/1131.

**Comment by daczarne** [comment]
> Hi! We appreciate every contribution. I'm not convinced yet, that plotly match our requirements. We'll discuss this in #1131.

I think this is a common confusion between Plotly the company and plotly the tool/library (developed by its name-sake company). As a JS data viz library Plotly is equivalent with other libraries included in devicons (like Flask, or Pandas). The base JS implementation can be found [here](https://github.com/plotly/plotly.js). The library is also available for [Python](https://github.com/plotly/plotly.py), [R](https://github.com/plotly/plotly.R), [Julia](https://github.com/plotly/Plotly.jl).

The other product that is mentioned in #1131 is Dash. This is another product by the same company (Plotly), for building Dashboards. It uses a Flask backend and React components as its building blocks. It allows for any other Python library to be used in its backend (like Plotly.py or matplotlib for example).

**Comment by amacado** [comment]
I'll re-run the bot. The icon looks suspicious in the "zoomed" screenshot (only a black square)

**Comment by amacado** [comment]
I checked it: It's because of the color removal by icomoon. Not sure why the "listed" view works fine (even in black/white) but the zoomed version does not. I tried it by manually uploading the icon and got the same results. I'm not 100% sure how to proceed, should we merge it and see what the final icon looks like?

**Comment by luizcarloscf** [comment]
Is there something I could do in the svg icons?

**Comment by amacado** [comment]
@luizcarloscf can you download the file i provided and verify that the icon looks alright in the demo?

**Comment by luizcarloscf** [comment]
I download the file and it looks ok. Here is a screenshot of the conversion:
print

**Review by amacado — APPROVED** [review]

**Pull request merged**
