### PR TITLE
new icon: vite (original, original wordmark)

### PR DESCRIPTION
**Pull request by AcmeGamers**
## Double check these details before you open a PR

- [ ✔ ] PR does not match another non-stale PR currently opened
- [ ✔ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ✔ ] PR's base is the `develop` branch.
- [ ✔ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ✔ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ✔ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date.
https://www.vite.org/

### CODE REVIEW

**Comment by kilian-paquier** [comment]
Hello @AcmeGamers, I reviewed your PR https://github.com/devicons/devicon/pull/1253, can you follow the recommandations and standards for this PR too ?

**Comment by AcmeGamers** [comment]
> Hello @AcmeGamers, I reviewed your PR #1253, can you follow the recommandations and standards for this PR too ?

For sure, I will get them fixed in a matter of a moment

**Comment by a3510377** [comment]
did u finished that? bro
(This sentence was translated by google

**Comment by Snailedlt** [comment]
@AcmeGamers Please read and implement the changes listed above when you have time

**Comment by Snailedlt** [comment]
Let us know if you need any help with the changes :)
We can collaborate on the PR if you want

**Comment by Snailedlt** [comment]
Closed bacuase the PR was stale, and replaced with #1472

**Pull request closed without merging**
