### PR TITLE
new icon: webflow (plain, original)

### PR DESCRIPTION
**Pull request by JorchCortez**
adding webflow icons and editing devicon.json
small extra change on devicon.json: formatted json

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date

[Webflow's website](https://webflow.com/)

## Notes

This logo was requested on Issue #999( Icon request: Webflow )

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
I suggest keeping the `plain` version, and use that one as the `original`. What do you think? :)

**Comment by JorchCortez** [comment]
Sure thing, changes are up 👍🏻 :)

**Comment by Thomas-Boi** [comment]
Hi @JorchCortez I think this is due to the `clipPath` attribute. Can you convert the SVG to use just `<path>`?

**Comment by Thomas-Boi** [comment]
Also, no rush but we are doing a release soon. If you can get it in within the next few days, it'll be include in this release. Else, it'll be in the next release

**Comment by JorchCortez** [comment]
@Thomas-Boi Perfect let me get to it and I'll update ASAP :)

**Comment by JorchCortez** [comment]
@Thomas-Boi Okay change is up it should work this time 👍🏼

**Review by Thomas-Boi — APPROVED** [review]
Sweet, this looks great now 👍 Thank you for your contribution.

**Pull request merged**
