### PR TITLE
new icon: opensuse (original, original-wordmark, plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by jusuchin85**
# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
https://en.opensuse.org/openSUSE:Artwork_brand#Logo

---

Resolves: #1074

### CODE REVIEW

**Review by Thomas-Boi — CHANGES_REQUESTED** [review]
Hello, please fix the filenames in the PR so it has the icon name as well

**Comment by Thomas-Boi** [comment]
Also, I'll make a build after this icon. If you make any other PR afterwards, it'll be in the next release

**Comment by jusuchin85** [comment]
> Hello, please fix the filenames in the PR so it has the icon name as well

Ah sorry! I missed including the tech name in the icon filename. Updated, @Thomas-Boi 

> Also, I'll make a build after this icon. If you make any other PR afterwards, it'll be in the next release

No worries! I think there're a few more to come after this, so it can come in the next release 😄

**Review by Thomas-Boi — APPROVED** [review]
This looks great 👍 Thank you for your work. I'll now make the next build

**Comment by Thomas-Boi** [comment]
@jusuchin85 rerunning the check script yields this result. Don't worry about the version name part. This is caused by GitHub merging the old and new check script => it has both the faulty and the good code. I'll check your other PRs too and tag you if they need fixing.

**Pull request merged**
