### PR TITLE
Newicons (c3, embeddedc, labview)

### PR DESCRIPTION
**Pull request by mjlabe**
Added asm, c3, embeddedc, and labview, but I broke the wordmark classes for the icons that don't actually have wordmark icons (like c-plain-wordmark). Could someone please fix that before merging? Why does that exist anyway?

### CODE REVIEW

**Comment by mjlabe** [comment]
Will do!

**Comment by Berkmann18** [comment]
@mjlabe Also have a look at #11 where @konpa compiled a huge list of icons and where people commented suggestions.

**Comment by iamclaytonray** [comment]
@Berkmann18 - this is definitely a great list and we can use this as a reference point moving forward but I'd like to keep PRs and issues restricted to a single icon at a time. Trying to manage a list of over 100 icons can be a little challenging and will inevitably become out of sync. With isolated issues and PRs, we can keep things tidy and improve changelogs. Thanks so much!

**Comment by mjlabe** [comment]
Should just add the icons in the PRs and leave the devicons.css alone?

**Comment by mjlabe** [comment]
Finally created PRs #282, #283, and #284. Please review and let me know if anything needs to be changed. Thank you.

**Comment by amacado** [comment]
I will close this pull request and review your new requests! :) Thanks in advance for your contribution @mjlabe

**Pull request closed without merging**
