### PR TITLE
new icon: 3dsmax (original, plain)

### PR DESCRIPTION
**Pull request by juniornsantos**
~~###Adding a New Icon?~~
- ~~Add autodesk-3ds-max-product-icon.svg~~

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Hi there! Thank you for submitting a PR 🙇 

I see it's your first time contributing to us. Please read our wiki to know what icons are accepted, and how to request/submit new icons. In particular I'd like you to take a look at this wiki page: [Overview-on-Submitting-Icons](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons), and create a new PR following those guidelines

**Comment by lunatic-fox** [comment]
🆗 This pull request is now ready to be reviewed.

**Review by Panquesito7 — APPROVED** [review]
Looks great. Thanks! 🚀

image

image

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️ 
Thank you for the contribution! 🙇

**Pull request merged**
