### PR TITLE
new icon: lodash (original, plain)

### LINKED ISSUE #1837: [ICON REQUEST]: lodash
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

A modern JavaScript utility library delivering modularity, performance & extras

### Links and sources

Check out the [lodash website](https://lodash.com/)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by weh**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1837**

## Link to prove your SVG is correct and up-to-date.

https://lodash.com/

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Looking good! Padding on the icons should be removed here too :)

**Comment by weh** [comment]
Removed padding and rebased to `develop`

**Review by Snailedlt — APPROVED** [review]
Looks perfect now! 🥇 
Great job as always @weh 🚀

**Review by lunatic-fox — CHANGES_REQUESTED** [review]
Great contribution! 👍🏼
Just some tiny adjustments. 🔧

**Review by lunatic-fox — APPROVED** [review]
Everything seems to be okay now! 👍🏼 
Thank you for this contribution! 🚀
image

**Review by canaleal — APPROVED** [review]
Great stuff. All is good.

**Comment by Snailedlt** [comment]
Merging this since it has two approvals :)

**Pull request merged**
