### PR TITLE
new icon: rails (plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by maltejur**
Old:
Screenshot 2021-04-08 205802

New:
Screenshot 2021-04-08 205829

This is how their website now looks:
Screenshot 2021-04-08 205906

### CODE REVIEW

**Comment by Panquesito7** [comment]
Hmm, [this](https://github.com/devicons/devicon/pull/554/checks?check_run_id=2300055587) is failing because of the commit title. See https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview for more information.

**Comment by Panquesito7** [comment]
I think it's only with the commit title. Once I tried renaming the PR, re-running the workflow, and it didn't work. It only worked by changing the commit title.

**Comment by Thomas-Boi** [comment]
I think I know what went wrong. The `peek` script only checks icons that haven't been added to to `icomoon.json`. Since we do have a current `rails` entry, the script is not seeing the new entry.

I'm looking into a possible fix. The easiest one I can think of is removing the `rails` entry in the `icomoon.json`

**Comment by Thomas-Boi** [comment]
@maltejur the only fix would be to modify the `icomoon.json` unfortunately. There are two ways to do so, either edit it in the json or change it using the Icomoon website.

Edit it in the JSON:
- Open the `icomoon.json` in your code editor. You might have to format it cause the file is truncated.
- Find the entry for `rails` and delete ONLY those entries.
- Save the file, commit and push again.

Edit it using the Icomoon Website:
- Go to this [page](https://icomoon.io/app/#/select)
- In the top left corner, there's a *Import Icons* button. Click on it and find the `icomoon.json` in the your file system.
- This will load all the icons from the project into Icomoon. There might be a popup: accept "Yes" for config options.
image

- Use the search box to find the `rails` icons. Delete them.
image

- At the bottom right, there's a *Generate Font* button. Click on it.
image

- There might be a popup talking about strokes and fills. Press "Continue"
image

- Click "Download"
image

-This will download a zip file to your computer. Open it and select only the `selection.json`. 
-Rename the file to `icomoon.json`. Add this new one to your local repo, commit, then push again.

Please try those steps. I'm 99% sure that they'll work.

**Review by Panquesito7 — APPROVED** [review]
LGTM. Thank you for your contribution! 👍 🎉

**Review by Thomas-Boi — APPROVED** [review]
This looks great now. Thanks @maltejur for putting in the extra work.

I'll look into a solution so this won't happen again in the future.

**Comment by maltejur** [comment]
Thanks for the detailed fix @Thomas-Boi

From https://github.com/devicons/devicon/blob/master/.github/scripts/icomoon_peek.py
```py
args = arg_getters.get_selenium_runner_args(True)
new_icons = filehandler.find_new_icons(args.devicon_json_path, args.icomoon_json_path)

# get only the icon object that has the name matching the pr title
filtered_icons = find_object_added_in_this_pr(new_icons, args.pr_title)

if len(new_icons) == 0:
    sys.exit("No files need to be uploaded. Ending script...")

if len(filtered_icons) == 0:
    message = "No icons found matching the icon name in the PR's title.\n" \
    "Ensure that a new icon entry is added in the devicon.json and the PR title matches the convention here: \n" \
    "https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#overview.\n" \
    "Ending script...\n"
    sys.exit(message)

# print list of new icons
print("List of new icons:", *new_icons, sep = "\n")
print("Icons being uploaded:", *filtered_icons, sep = "\n", end='\n\n')

runner = None
try:
    runner = SeleniumRunner(args.download_path, args.geckodriver_path, args.headless)
    svgs = filehandler.get_svgs_paths(filtered_icons, args.icons_folder_path, True)
    screenshot_folder = filehandler.create_screenshot_folder("./") 
    runner.upload_svgs(svgs, screenshot_folder)
    print("Task completed.")
```
Why doesn't the find_object_added_in_this_pr function just take all the icons?

**Pull request merged**
