### PR TITLE
[FEAT]: "New Twitter Icon"

### PR DESCRIPTION
**Pull request by Yashh56**
Adding a New Twitter Icon   #1890

### CODE REVIEW

**Comment by Yashh56** [comment]
I am sorry for all the mistakes ;) I am new to Open source and GitHub

**Comment by Yashh56** [comment]
Is there is problem in this branch? it is merging the file in develop branch of devicons.

**Comment by Yashh56** [comment]
should I change the name of Twitter? @Snailedlt

**Comment by Snailedlt** [comment]
> Is there is problem in this branch? it is merging the file in develop branch of devicons.
> 

Yes. The PR is set to merge into develop, but the branch had commits from the master branch. To fix this you can either revert the commit or make a new branch from the develop brnach and apply the changes on that. Whichever is easier for you :)

The name should be twitter, but you can add `x` as an altname (see the wiki for how to edit devicon.json)

**Comment by Yashh56** [comment]
Then what should be the name of new branch ? @Snailedlt

**Comment by Yashh56** [comment]
Hey @Snailedlt Please Review The New PR

**Comment by Yashh56** [comment]
Hey @Snailedlt Is this PR is right ?

**Comment by Snailedlt** [comment]
Duplicate of #1912

**Pull request closed without merging**
