### PR TITLE
new icon: Axios (plain,plain-wordmark)

### LINKED ISSUE #1056: Icon request: Axios
### About the icon

Popular Technology

### Links and sources

https://www.axios.com/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JorchCortez**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1056**
> quick note here that the website for this issue is wrong (if referring to Axios http since the current link given is for a sort of blog page)

## Link to prove your SVG is correct and up-to-date.

[Axios http website](https://axios-http.com/)

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Don't worry about the check-bot's message for now. We are currently fixing the issue.

**Review by williamsimionatto — DISMISSED** [review]

**Comment by JorchCortez** [comment]
@Thomas-Boi Thanks, I did saw in another PR that the same error popped so I thought it was the case 😅 If there's any change needed though let me know 👍🏼

**Comment by Thomas-Boi** [comment]
Hi @JorchCortez can you rebase this branch off the latest develop? That should fix the peek icon issues.

**Review by amacado — APPROVED** [review]
Looks good to me! Thanks for the contribution!

**Comment by amacado** [comment]
My mistake: did not squash-merged, @Thomas-Boi is this a big problem?

**Comment by Thomas-Boi** [comment]
> My mistake: did not squash-merged, @Thomas-Boi is this a big problem?

I don't think so. It all depends on how many commits are there. This one only has 1 commit so it should be fine. Even if there's more than one, the only issue is it makes for a cluttered history but no problem with our pipeline.

**Pull request merged**
