### PR TITLE
add icon: ballerina (original, plain, line, original-wordmark, plain-wordmark, line-wordmark)

### PR DESCRIPTION
**Pull request by Zach128**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

* [ballerina.io](https://ballerina.io/)
* [ballerina playground](https://play.ballerina.io/)

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
Hello! Thank you for your contribution! Some suggestions:
- Please do not auto-format the `devicon.json`. You introduct a huge changeset which is not required.
- I'm not sure about the wordmark version. Can you prove that this is the original wordmark? I would assume it's only the font (which includes the icon). But your pr submits the font plus icon

**Comment by Zach128** [comment]
Hello, and thanks for the welcome. Regarding the points:
* Sorry about that. Will remove the autoformatting and recommit just my addition.
* Regarding the wordmark, would you please elaborate? I'm unfamiliar with it and may have misunderstood. The font and icon was just my joining of the two main logos (the original SVG plus the logo on their homepage)

**Comment by Zach128** [comment]
Hi @Panquesito7. I fixed the title so the Peek Icons check should read it fine. Would you rerun it please?

**Comment by amacado** [comment]
@Zach128 sadly out bot does not parse updated titles. You have to re-create the pr.. :)

**Comment by Zach128** [comment]
Hi @amacado. I see, no problem. I'll re-create it.

**Comment by Zach128** [comment]
Re-created the pr [here](https://github.com/devicons/devicon/pull/1205)

**Pull request closed without merging**
