### PR TITLE
update icon: astro (plain-wordmark, plain, original-wordmark, original)

### PR DESCRIPTION
**Pull request by cyberalien**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features
Fixes invalid color in `astro-plain-wordmark.svg`

**This PR closes [1542](https://github.com/devicons/devicon/issues/1542)**

### CODE REVIEW

**Comment by cyberalien** [comment]
Optimised icons, including other variations to make all variations similar.

Does it require changing variations list in title? Other than one fixed icon, the rest are just optimised.

**Comment by Snailedlt** [comment]
@cyberalien thanks, yes the title is used for some workflows to check the icons with `peek-bot` and `check-bot`

**Review by Snailedlt — DISMISSED** [review]
Thank you for the contribution! :bow:

**Review by lunatic-fox — APPROVED** [review]
Remove `fill-rule` and ungroup. Hope that's ok! 🙂
Approved! ✔
Thanks for this contribution! 🚀

**Review by Snailedlt — APPROVED** [review]

**Pull request merged**
