### PR TITLE
new icon: magento (original, original-wordmark, line)

### PR DESCRIPTION
**Pull request by Thomas-Boi**
Taken from #193. The `plain` versions are the same as the `original` so they were removed.

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
The `post comment` bot is trying to upload 3 images. However, the API would fail at the 3rd image. Action result [here](https://github.com/devicons/devicon/runs/2696629605?check_suite_focus=true)
image

I think this is more of an issue with their API than us. I'll contact them and see if they can offer any solution.

**Review by Panquesito7 — COMMENTED** [review]
Maybe you should consider optimizing these SVG's.

**Comment by Thomas-Boi** [comment]
I'll check what's up with the line version

**Review by Panquesito7 — COMMENTED** [review]
Are all these SVG's optimized with some tool? It seems they aren't. 🤔

**Comment by Thomas-Boi** [comment]
They aren't optimized yet since we are using a new optimization step. See this [issue](https://github.com/devicons/devicon/issues/614)

**Review by Panquesito7 — APPROVED** [review]
Looks good. Great work, @Thomas-Boi! 👍 🎉

**Pull request merged**
