### PR TITLE
new icon: Added dynamodb svg

### PR DESCRIPTION
**Pull request by SubhamSubhasisPatra**
As per this issue https://github.com/devicons/devicon/issues/1611, Added the  dynamodb svg.

### CODE REVIEW

**Comment by ConX** [comment]
Hi @SubhamSubhasisPatra, I think you will have to edit/resubmit your PR as you haven't included an updated `devicon.json`, and you haven't used the template in the PR. Check [this](https://github.com/devicons/devicon/blob/1119b9f84c0290e0f0b38982099a2bd027a48bf1/CONTRIBUTING.md#overview) for more details. 

PS: I am also new to the project and not a maintainer ;)

**Comment by SubhamSubhasisPatra** [comment]
Hi @ConX , Thanks for your feedback. I'll update the changes accordingly .

**Comment by ConX** [comment]
Hi @SubhamSubhasisPatra, I forgot to mention in my previous message that according to the instructions, the target repo of the PR must be the `develop` branch.

**Comment by lunatic-fox** [comment]
Hello there @SubhamSubhasisPatra!
- You will need to make another pull request basing on `YourFork:develop` branch to `devicon:develop`.
- Please take a look at the [Wiki - Overview on Submitting Icons](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [SVG Standards](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [SVG Versions](https://github.com/devicons/devicon/wiki/SVG-Versions)
- [Updating `devicon.json`](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)
- You can also check the [Devicon Discord Server](https://discord.gg/hScy8KWACQ)

Wish for the best! 😀

**Comment by SubhamSubhasisPatra** [comment]
Hi  @lunatic-fox  and @ConX , Will make the changes . Thanks .

**Comment by dinbtechit** [comment]
Looks like this is the old AWS icons. Please use the new ones - https://aws.amazon.com/architecture/icons/ 

Here is the latest one: 
image

**Comment by Snailedlt** [comment]
Duplicate of #1770
Which has already been merged to `develop`
Thank you for the contribution regardless!

**Pull request closed without merging**
