### PR TITLE
update icon: helm (original, line)

### LINKED ISSUE #1613: [BUG] HELM and nano icons do not build on IcoMoon
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

When trying to build the font for the current  `develop` branch, I found that the `HELM` and `nano` icons introduce issues.

Specifically, the `nano` icons (`nano-original.svg`, `nano-original-wordmark.svg`), completely break the IcoMoon font generation step, as shown below:

image

On the other hand, the `HELM` icon results to the following alert from IcoMoon:

image

When generating the font with the `HELM` icon selected, IcoMoon asks for it to be deselected before proceeding.

### Possible fixes or solutions

- Delete icons from the `develop` branch
- Add to the automation the appropriate checks, if those haven't been added since those icons were merged to `develop`.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ConX**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

- Fixes the stroke issue mentioned in #1613
- Adds line version
- Updates the color in the `devicon.json` file to the official color

**This PR closes #1613**

### CODE REVIEW

**Review by lunatic-fox — CHANGES_REQUESTED** [review]
Hello again @ConX!

I've removed `plain` version, because the `original` is a monochromatic icon that can be aliased as `plain`.

I need that you resize both versions to 128px squared icon, then optimize them.

The reason for the alert on Icomoon, as it said, was because the previous icons have a lot of strokes and other unnecessary style information. So, thank you for noticing that and have made this pull request. 😁

**Comment by ConX** [comment]
Hi @lunatic-fox, I resized the icons to 128x128px and ran `svgo` to optimize. Let me know if there is anything else needed.

Thanks for explaining the reasoning on whether an icon needs the `plain` or not.

**Review by lunatic-fox — APPROVED** [review]
Approved! ✔
Thank you for this contribution! 🚀

**Review by Snailedlt — APPROVED** [review]
Thank you for your contribution! ✔️

**Pull request merged**
