### PR TITLE
Remove package-lock.json

### PR DESCRIPTION
**Pull request by theblobscp**
Usually, the package-lock file is ignored. However, you decided to keep it around. This PR helps to reduce repo size by deleteing the file

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
@theblobscp what are the reasons you suggest to remove `package-lock.json`. As in the official documentation is written:

> [..] This file is **intended to be committed into source repositories**, and serves various purposes [..]

Look here for more information: https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md

**Comment by theblobscp** [comment]
It takes up a lot of space in the repo. That's kinda it.

**Comment by amacado** [comment]
Currently it takes 190 KB (5305 lines,), I don't think this is a problem in terms of repository size compared to the advantages. @Thomas-Boi @Panquesito7 what do you think?

**Comment by Thomas-Boi** [comment]
Storage size is not a problem if the file is important. The `devicon.json` is huge but we keep it since it's important.

I've never heard of the `package-lock.json` being ignored by repo. All of the repos that I know of keep either a `package-lock` or a `yarn-lock` around. We've had issues where `npm` doesn't run properly due to a faulty `package-lock.json`. The link amacado provided also explained more of what the file does if you are interested.

I don't see any benefits to removing the file. I'll close the PR for now. If there're any valid reasons to doing this, we can reopen it.

**Comment by theblobscp** [comment]
I HAVE A REASON

**Comment by theblobscp** [comment]
When I try to npm install it says the package-lock is too old, so I cant actually install them

**Comment by amacado** [comment]
>I HAVE A REASON

Caps lock is considered as a very rude, screaming interpuction and this is against our understanding of a welcoming, friendly interaction. I would highly appreciate if you take a look at our [Contributor Covenant Code of Conduct](https://github.com/devicons/devicon/blob/develop/CODE_OF_CONDUCT.md). 

>When I try to npm install it says the package-lock is too old, so I cant actually install them

A more detailed walktrough woud make it easier to reproduce your steps. I just tried checking out the `develop` branch and running `npm install` on a fresh clone of the repository. I'm unable to reproduce any error near to "package-lock is too old". The command works as expected. Altough it's worth to mention that there are some vulnerabilities pointed out by npm, they are not resulting in a "failed installation".

```
found 6 vulnerabilities (1 low, 3 moderate, 2 high) in 585 scanned packages
  run `npm audit fix` to fix 2 of them.
  1 vulnerability requires semver-major dependency updates.
  3 vulnerabilities require manual review. See the full report for details.
```

I will create a new issue to fix those vulnerabilities, but it's out of scope of this issue.

**Comment by theblobscp** [comment]
do you want my log then

**Comment by Panquesito7** [comment]
I agree with @Thomas-Boi. 👍

**Comment by theblobscp** [comment]
Yeah but I still can't compile the repo
Also I'm using the latest version of npm

**Comment by Panquesito7** [comment]
How are you trying to compile the repository? What errors does it display?

**Comment by theblobscp** [comment]
> How are you trying to compile the repository? What errors does it display?

I try to npm install and it shows this error
```powershell
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.      
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\user\\OneDrive\\Documents\\GitHub\\devicon\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.4.2 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\OneDrive\\Documents\\GitHub\\devicon\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\user\OneDrive\Documents\GitHub\devicon\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.4.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-07-19T20_38_15_322Z-debug.log
```

**Comment by theblobscp** [comment]
I found an alternative to the file size. You can just use yarn. However, that will take a while to update on everyone's machines.

**Pull request closed without merging**
