### PR TITLE
Bugfix/fix in devicon.json

### PR DESCRIPTION
**Pull request by lunatic-fox**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

Removes unnecessary aliases of `sequelize` in `devicon.json`

**This PR closes NONE**

### CODE REVIEW

**Review by Snailedlt — APPROVED** [review]
That's a lot of commits for a small change, consider redoing the branch or rebasing on develop next time, so it's easier for reviewers to look through it :)

That said, nice catch 🕵️
Thanks for making a PR on it, very much appreciated 🙏

**Comment by Snailedlt** [comment]
@lunatic-fox 
By the way, it shouldn't be possible for contributors to add the same aliases... even more reason to ship your feature request ASAP :) ref: #1481

**Comment by lunatic-fox** [comment]
> That's a lot of commits for a small change, consider redoing the branch or rebasing on develop next time, so it's easier for reviewers to look through it :)
> 
> That said, nice catch 🕵️
> Thanks for making a PR on it, very much appreciated 🙏 
> 

I'll be doing that next time.
I got a little bit shocked by the amount of commits.

**Comment by Snailedlt** [comment]
@lunatic-fox hehe, yeah... In this case there was no issue, and it's rarely an issue for devicons since we do squash merging which squashes all of the commits into a single commit on the develop branch. However it could become an issue if there's a big feature, where you make multiple changes :) So just sort of a side note

**Comment by Snailedlt** [comment]
Btw, we should probably add this  alias/base duplicate value check to our `check-bot`, so I made an issue (#1486) to make note of it :) I've done some resent changes to the `check-bot` myself, so I'll probably end up adding it myself

**Comment by lunatic-fox** [comment]
> Btw, we should probably add this  alias/base duplicate value check to our `check-bot`, so I made an issue (#1486) to make note of it :) I've done some resent changes to the `check-bot` myself, so I'll probably end up adding it myself

That's great!
I'm still learning how to work with bots, as soon as got more confident I'll help with that too. 🙂

**Pull request merged**
