### PR TITLE
new icon: Jupyter (original, original-wordmark, plain, plain-wordmark)

### LINKED ISSUE #295: Icon request: Jupyter
### About the icon
Jupyter is a popular tool to write python notebooks, with its own file format based on JSON.
In an app offering to download both plain Python code and notebook, I would use the two relative icons to choose.
### Links
https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
### Preview

### PR DESCRIPTION
**Pull request by Panquesito7**
Closes #295.

I added an icon for the [Jupyter Project](https://jupyter.org/) language.
`original-wordmark` was taken from [Wikipedia](https://en.wikipedia.org/wiki/Project_Jupyter). `plain-wordmark` was taken and slightly modified from https://icon-icons.com/icon/Jupyter/132275#128. `original` was taken from https://icon-icons.com/icon/jupyter-logo/169452. `plain` was taken and slightly modified from https://icon-icons.com/icon/jupyter-logo/145142. I resized all icons using the [`resize-image`](https://www.iloveimg.com/resize-image/resize-svg) tool. 🙂

This is how they look:

Jupyter Notebook original-wordmark icon Jupyter Notebook plain-wordmark icon Jupyter Notebook original icon Jupyter Notebook plain icon

If I missed up anything please let me know. Thank you.

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
When I compare your version of jupyter to the [projects page ](https://jupyter.org/) version I noticed two things:

1) The variant you contributed should better be namend `jupyter-original-wordmark.svg` (you can see a variant of the icon without the wordmark on the project page aswell)
2) The plain version looks compressed in comparison to the orignal. You can clearly see that the three dots around the actual icon are more oval than round

**Comment by Panquesito7** [comment]
I will fix the mentioned issues. Thanks.

**Comment by Panquesito7** [comment]
Issues have been fixed now.

**Review by amacado — CHANGES_REQUESTED** [review]
`icons/jupyter/jupyter-original.svg` and `icons/jupyter/jupyter-plain.svg` looking good to me, but the others are still "squashed"

**Comment by Panquesito7** [comment]
> ...but the others are still "squashed"

Working on it.

**Review by amacado — APPROVED** [review]
Approved! :) Thanks for all the effort @Panquesito7. Jupyter will be included in our next release! :)

**Pull request merged**
