### PR TITLE
New icon: Kotlin (plain, plain-wordmark, original and original-wordmark)

### PR DESCRIPTION
**Pull request by ezSaldana**
## Added kotlin icon
I've added the plain and original with wordmark kotlin icons. Give it a check and let me know if there's something I should change.

### Image
Screen Shot 2020-09-23 at 16 46 03

### Issue Reference
#198 & #121

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by ezSaldana** [comment]
Done!
Let me know if everything's ok!

**Review by amacado — CHANGES_REQUESTED** [review]
Kotlin icon versions looking great, but could you remove the flutter icons from this pull request since it's not related to Kotlin?

`icons/flutter/flutter-original.svg`
`icons/flutter/flutter-plain.svg`
`icons/flutter/flutter.eps`

They should be better placed in the #296 pull request :)

**Comment by ezSaldana** [comment]
Ready!

**Review by amacado — APPROVED** [review]

**Pull request merged**
