### PR TITLE
Add the public-upload-to-imgur action

### PR DESCRIPTION
**Pull request by Thomas-Boi**
Hello there,

This PR should allow us to upload images to the GitHub comments using GitHub Actions. You can see an example in the message below.

### CODE REVIEW

**Review by amacado — COMMENTED** [review]
This is so cool! I love it! Amazing work! 👍🏻 
I was thinking about: Maybe we should create the action-repository under the domain of "devicon". We could fork your repo `Thomas-Boi/public-upload-to-imgur` so it will remain credit to your work but we have it in the scope of this project. Happy to hear your thoughs about it.

**Comment by Thomas-Boi** [comment]
Hey amacado,

I think that's a good idea. I'll see if I can do it today and create a repo in our organization

**Comment by amacado** [comment]
Think that's a good idea. Can you add me into the devicons organization please? I can fork my repo and upload it there. I'm also planning adding more documentations and publish it as well.

Sorry, did not get notified about your edit and did not see that you weren't added to the orga yet. Sorry for the delay, you have a invitation.

**Comment by amacado** [comment]
> Think that's a good idea. Can you add me into the devicons organization please? I can fork my repo and upload it there. I'm also planning adding more documentations and publish it as well.

Sorry, did not get notified about your edit and did not see that you weren't added to the orga yet. Sorry for the delay, you have a invitation.

**Comment by Thomas-Boi** [comment]
Hey @amacado,

Thank you for the invite. However, it seems that I don't have the permission to create public repos in the devicon organization 😅. Can you give me permission to do this please?

**Comment by Thomas-Boi** [comment]
Hey @amacado,

Everything should be good for this PR. I've updated the new action and everything seems to work fine. Note that the multiple file input/glob has not been tested. I'll keep working on it since I'm planning to add more screenshots to the peek script plus make it a bit faster.

**Review by amacado — APPROVED** [review]

**Pull request merged**
