### PR TITLE
new icon: elasticsearch (original, original-wordmark, plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by kilian-paquier**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.elastic.co/fr/what-is/elk-stack
https://www.elastic.co/fr/elasticsearch/

### CODE REVIEW

**Review by Snailedlt — COMMENTED** [review]
Any particular reason you chose `#00bfb3` as the main color?

**Comment by kilian-paquier** [comment]
Hello @Snailedlt, yes, i followed the color given here for each logo of the ELK stack : https://www.elastic.co/fr/what-is/elk-stack (https://www.elastic.co/static-res/images/elk/elk-stack-elkb-diagram.svg). So it is "green" for elasticsearch, blue for beats, yellow for logstash and pink for kibana. As for this specific color tone, I got all the icons from the official website (they included the SVGs) except for the wordmark ones.

https://www.elastic.co/fr/elasticsearch/ -> https://static-www.elastic.co/v3/assets/bltefdd0b53724fa2ce/blt36f2da8d650732a0/5d0823c3d8ff351753cbc99f/logo-elasticsearch-32-color.svg

https://www.elastic.co/fr/kibana/ -> https://static-www.elastic.co/v3/assets/bltefdd0b53724fa2ce/blt4466841eed0bf232/5d082a5e97f2babb5af907ee/logo-kibana-32-color.svg

https://www.elastic.co/fr/beats/ -> https://static-www.elastic.co/v3/assets/bltefdd0b53724fa2ce/blta3a797dfc3d80de3/5d0c1b1977f34fd55839ab58/logo-beats-32-color.svg

https://www.elastic.co/fr/logstash/ -> https://static-www.elastic.co/v3/assets/bltefdd0b53724fa2ce/blt8b679e63f2b49b27/5d082d93877575d0584761c0/logo-logstash-32-color.svg

**Comment by Snailedlt** [comment]
@kilian-paquier Okey neat!
Just double checked the color and it's the same hex code, so all good! 👍

**Review by Snailedlt — APPROVED** [review]

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Merge conflicts need to be solved before merge

**Comment by Snailedlt** [comment]
@kilian-paquier more merge conflicts :/

**Comment by kilian-paquier** [comment]
@Snailedlt Fixed :)

**Comment by Snailedlt** [comment]
@kilian-paquier sorry again, was a bit early on the trigger there :/
Could you go ahead and fix again? 😅

**Comment by kilian-paquier** [comment]
> @kilian-paquier sorry again, was a bit early on the trigger there :/ Could you go ahead and fix again? 😅

Done :D

**Review by Snailedlt — APPROVED** [review]
LGTM!
Thanks for the contribution!

**Pull request merged**
