### PR TITLE
new icon: Mastodon (original, plain, line)

### PR DESCRIPTION
**Pull request by Imoptimal**
## Double check these details before you open a PR

- [&check; ] PR does not match another non-stale PR currently opened
- [&check; ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [&check; ] PR's base is the `develop` branch.
- [&check; ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [&check; ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [&check; ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://joinmastodon.org/

### CODE REVIEW

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Hi, Could you please make a new branch and PR, and base the branch itself on develop?
Atm the branch base is master, while the PR base is develop. This is what causes these additional commits to be shown:
image

EDIT:
In case you're unsure how to do it.
1. First checkout develop
`git checkout develop`
2. Then make the new branch
`git checkout -b new_branch_name`
3. Finally, make the changes you want for the PR :)

**Comment by lunatic-fox** [comment]
Thank you for this PR contribution!
However, Mastodon is a [Social Media Platform](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F), that is not allowed to this project scope.
Closed.

**Comment by Imoptimal** [comment]
And big social media like Twitter and Facebook were allowed and included?!

**Comment by lunatic-fox** [comment]
> And big social media like Twitter and Facebook were allowed and included?!

Hello there! Good question! 🚀

That happens because some icons were added before the [first Wiki version](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F/93c45333ed97c6f7a91950f3821d41d3f3982bb5) which was on December 28, 2021.

Even I wanted to remove icons that no longer fit the project anymore, however we decided to keep them for [backwards compatibility](https://github.com/devicons/devicon/issues/1445#issuecomment-1306578293).

For instance, Twitter and Facebook were added in January 6, 2017, along with Google icon in the same [pull request](https://github.com/devicons/devicon/commit/158fbb74b56f26b37c63c5118d58f6f6d6121e6a). Even a note was created to avoid pull requests with icons of different technologies: 
- [First Wiki edition on December 28, 2021](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons/24496afb83ca756f30f9894a2dd9d26646a7a694)
- [Second Wiki edition on December 29, 2021](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons/f398fdf1ede11d3093eb711dcf28c03f69226320) - *specifies that icons of different technologies should be splitted into their own pull requests.*

We still accept updates to old icons that exceed the Wiki rules, but we don't accept new icons that don't follow these rules.

I hope that you understand the reasons to not accept your pull request and if you want to chat with us, we have the [Devicon Discord Server](https://discord.gg/hScy8KWACQ).

**Pull request closed without merging**
