### PR TITLE
Added new icons for tailwindCSS #1489 fixed.

### PR DESCRIPTION
**Pull request by theabhayprajapati**

### CODE REVIEW

**Comment by theabhayprajapati** [comment]
### New TailwindCSS icons
added 
image

and this one 
image

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Hi there, thanks for making a PR!
Is this your first time contributing to devicons? :)
If so, please check out our wiki page on [Updating An Icon](https://github.com/devicons/devicon/wiki/Updating-An-Icon)

Here's some pointers as to what needs to be fixed first:
- The PR base is `master` but should be `develop`
- The PR title needs to be changed. Try re-creating the PR and adding `?quick_pull=1&template=new_icon.md` to the end of the url before pressing `create pull request`
- The icon filenames are invalid. See [SVG-Versions](https://github.com/devicons/devicon/wiki/SVG-Versions) for valid names

Let me know if you need any help, and feel free to join our discord if you prefer to chat there :)
https://discord.gg/Yp4wSU6sh4

**Comment by theabhayprajapati** [comment]
@Snailedlt  hey I have doubt 🤔 with the third point: which says file names are invalid as it should be **SVG**,  however it's svg itself right now.
 #1489

**Comment by Snailedlt** [comment]
> @Snailedlt  hey I have doubt 🤔 with the third point: which says file names are invalid as it should be **SVG**,  however it's svg itself right now.
>  #1489

Sure, thanks for asking :)
The problem isn't the filetype, but the filename itself. It should follow the pattern described in the SVG-Versions I linked. I recommend reading through the wiki links I sent, to understand the process of making a PR :)

**Comment by theabhayprajapati** [comment]
Hii 👋 @Snailedlt I read the wiki and your recommendation created a new PR while following the process.

**Comment by theabhayprajapati** [comment]
#1493

**Pull request closed without merging**
