### PR TITLE
add all available icons to readme

### PR DESCRIPTION
**Pull request by timbogdanov**
As part of the Hacktoberfest I would like to contribute to the readme with a photo of all available icons on devto.
The idea came to me since I use devicons very often.

Let me know if you'd like any edits.

### CODE REVIEW

**Comment by amacado** [comment]
@timbogdanov hello! :) I like your idea.

I would suggest to create a `/doc/assets/img/` folder to store the screenshot instead of publishing it via an external url.

**Comment by timbogdanov** [comment]
@amacado Thank you for the suggestions. Made those changes!

**Comment by amacado** [comment]
@Thomas-Boi I like this idea, what do you think? (Open discussion)

**Comment by Thomas-Boi** [comment]
I like the idea of having a reference to all the icons. The image that you made was very well done too. However, I want to bring up two questions:

1. How do we update the PNG as time goes on and more icons get created?
2. Is it possible to add this functionality or something similar to our GitHub Page website? This would allow people to search for a specific icon and check if it exists. This might also make it easier to update since we will update the Page periodically as well.

Also, just curious @timbogdanov, why did you choose to implement this feature? What problems does it solve for you?

**Comment by amacado** [comment]
> How do we update the PNG as time goes on and more icons get created?

This is a good question!

**Comment by timbogdanov** [comment]
@Thomas-Boi that if I understand correctly, you'd like something that automatically creates a png and create the png link and pushes it to the read me. Correct me if I'm wrong. Unfortunately I've only been doing web development for the past 8 months, and I don't think I'd know how to do that yet. The point of this icon preview for me was to contribute to an open source project for hacktoberfest. 

I chose to implement this feature because I am like many out there a visual learner. When I see a representation of something, in this case open source dev icons, I quickly understand what is going on, the use cases, and etc.

**Comment by Thomas-Boi** [comment]
Hey @timbogdanov,

It's great that you want to contribute to an open source project for Hacktoberfest. I just wanted to ask why you are using this specific solution so that we can understand your issue. Sometimes, an issue can be solved in multiple ways.

> I chose to implement this feature because I am like many out there a visual learner. When I see a representation of something, in this case open source dev icons, I quickly understand what is going on, the use cases, and etc.

I am more a visual learner too :). I agree that it's great to have a visual on what you are using, especially for something like Devicons. However, I think that our [Devicons website](https://devicon.dev/) addresses this issue very well. Users can view all of the icons in their proper form. They can also search for a specific icon and view all of the available versions that we have.

As for updating the PNG, if the PNG is worthwhile and easy to make we can consider doing it. However, I'm not seeing a clear advantage over the Devicons website at the moment. I would suggest that you try using the site and see if it's helpful to you. If there's anything that we can make it better for you, let us know and we can look into it.

I hope that clears things up. Let me know if you find anything :)

**Comment by Thomas-Boi** [comment]
Hey @timbogdanov ,

Let me know if you have any feedback regarding the website. If you do, I would recommend opening a new issue so that everyone in the community can discuss it. Until then, I will close this PR.

Cheers,
Thomas

**Pull request closed without merging**
