### PR TITLE
new icon: karatelabs (original, original-wordmark, plain, plain-wordmark)

### PR DESCRIPTION
**Pull request by kilian-paquier**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.karatelabs.io/

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
What do you think about this: should we remove the `plain` and `plain-wordmark` and use `original` and `original-wordmark` as the font versions? After all, they're just one solid color.

Thanks.


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by kilian-paquier** [comment]
> What do you think about this: should we remove the `plain` and `plain-wordmark` and use `original` and `original-wordmark` as the font versions? After all, they're just one solid color.
> 
> 
> 
> Thanks.
> 
> 
> 
> 
> 
> __
> 
> [sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question
> 
> 

Yep 👍

**Comment by Panquesito7** [comment]
> > What do you think about this: should we remove the `plain` and `plain-wordmark` and use `original` and `original-wordmark` as the font versions? After all, they're just one solid color.
> > Thanks.
> > __
> > [sema-logo](https://semasoftware.com/gh)
> >       
> >         [
> >           
> >             sema-logo
> >           
> >         ](https://semasoftware.com/gh)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://semasoftware.com/gh)
> >         
> >         **Summary:** ❓ I have a question
> 
> Yep 👍

Cool, thanks! Let us know if you need any help. :)

**Comment by Snailedlt** [comment]
@Panquesito7 did the logos change? Original and Original wordmark have two colors (black and white), so they wouldn't work as fonts right?

**Review by Snailedlt — APPROVED** [review]

**Comment by Snailedlt** [comment]
Imo it looks good as it is. Plian have transparent instead of white person in the center. Seems fine to me :)

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Now the karatelabs original icons don't look like the original logos on their website. They should be black and white, not just black

**Comment by kilian-paquier** [comment]
> Now the karatelabs original icons don't look like the original logos on their website. They should be black and white, not just black

Reverted the commit

**Comment by Snailedlt** [comment]
Nice, thanks :)
Now the question is, should the plain icons be white or black?

**Comment by kilian-paquier** [comment]
> Nice, thanks :) Now the question is, should the plain icons be white or black?

Black obviously

**Review by Snailedlt — APPROVED** [review]
Thanks for your contribution! :heavy_check_mark:

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing!


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
