### PR TITLE
new icon: Eleventy (original, plain)

### PR DESCRIPTION
**Pull request by tylensthilaire**
Original and plain icons for [Eleventy](https://www.11ty.dev)

Jpeg logo for reference:
8ZfcJCXi_400x400

### CODE REVIEW

**Review by amacado — CHANGES_REQUESTED** [review]
Hello @tylensthilaire and thanks for your contribution!

When I take a look at the 11ty repo and website I always see the logo not squared (like in your contribution) but instead in a cuboid form:
image

Are you able to provide any official logo sources?

**Comment by tylensthilaire** [comment]
You're right. It's only squared off on their Twitter and favicon, likely because of the constraints of those formats.

Will update.

**Comment by amacado** [comment]
I will wait for @Thomas-Boi to resolve #414 so we can have a look at the font version.

**Comment by Thomas-Boi** [comment]
Hi @tylensthilaire ,

Unfortunately, we are running into some issues checking your SVGs. It seems that your forked repo is from an older version of our `master` branch. In order for us to check your icons, please pull our latest commit from our `develop` to your fork. 

You might find [this](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) link useful to update your repo. 

Cheers,
Thomas

**Comment by tylensthilaire** [comment]
Pulled in the latest from develop. Must have PRed in Develop instead of master by mistake.

**Comment by Thomas-Boi** [comment]
Hi @tylensthilaire ,

Thank you for your patient. It seems that we ran into an unexpected issue in our peek script. As you might know, our repo use [icomoon](https://icomoon.io/) to create our icons. Since this is a website, our script might run into issue selecting items whenever the site is updated. It seems to be what's happening here since there are similarity between this PR and #415.

In summary, the Icomoon app now show/not show certain elements depends on the color of the SVG that you upload. For more details, you can see [my comment](https://github.com/devicons/devicon/pull/415#issuecomment-753285672).

We will publish a fix and merge as soon as possible. When that happens, would you be ok with updating your repo one more time with this fix? We really appreciate your patient so far and we hope to see your icons in our repo soon.

Cheers,
Thomas

**Comment by Thomas-Boi** [comment]
Hi @tylensthilaire ,

We have merged our fix for the issue that we are seeing into develop. Can you please merge this fix into your repo please? If this doesn't fix the issue, I will personally check your icon myself 👍

**Comment by Thomas-Boi** [comment]
Hello,

Here is the icon version of your svg:
new_icons
screenshot_0

Everything looks good so we'll be merging your PR into the repo. Thank you very much for your work and patient while waiting for the issues to be fixed 😃

Happy New Year,

**Pull request merged**
