### PR TITLE
new icon: markdown (original)

### PR DESCRIPTION
**Pull request by tupaschoal**
svg_2

### CODE REVIEW

**Review by theblobscp — DISMISSED** [review]
My issue for this was closed due to duplicate, so uh thanks for making it an actual pr

**Comment by Thomas-Boi** [comment]
Hey @tupaschoal ,

Great work! Just need a tiny change: can you add a little bit of margin to the left and right of the SVG please? The sides look cut off compared to the [original](https://www.markdownguide.org/)

**Review by Thomas-Boi — CHANGES_REQUESTED** [review]
Hey @tupaschoal ,

Great work! Just need a tiny change: can you add a little bit of margin to the left and right of the SVG please? The sides look cut off compared to the [original](https://www.markdownguide.org/)

EDIT: I'd recommend scale down the SVG objects a bit so the ratio is maintained

**Comment by tupaschoal** [comment]
It should be fine now.

**Review by Thomas-Boi — APPROVED** [review]
This looks great now @tupaschoal! Great work as always 👍

**Pull request merged**
