### PR TITLE
update icon: protractor (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Protractor Website](https://www.protractortest.org/#/)
- [Protractor SVG Github](https://github.com/juliemr/protractor/blob/01d352eef1c2361fb2c7e54da2e6b92374d61824/logo.svg)

## Additional Notes

I was unable to find an official mark logo without the protractor text. As such, I used aliases for all the wordmark versions. 
The red color `#d51c2f` was used for the font SVGs. This color is taken from the lighter red on the protractor-original svg.

### CODE REVIEW

**Review by lunatic-fox — DISMISSED** [review]
Great one! 👍🏼
Thank you for this contribution! 🚀
*PS: Seems that SVG logo has different colors from PNG one, I mean, the `original` version.*
image
image

**Review by Snailedlt — DISMISSED** [review]
Great job once again!
The only place I could find the non-wordmark version was in the favicon... but not sure that should count, since it's only used as the website icon here:
image
[https://www.protractortest.org/img/favicon.ico](https://www.protractortest.org/img/favicon.ico)

**Comment by Snailedlt** [comment]
@canaleal Once again I'll let you choose whether or not you wanna merge, or add the non-wordmark version(s)

**Comment by canaleal** [comment]
I'm gonna add the non-wordmark version.

**Review by weh — APPROVED** [review]
LGTM 👍

**Review by Snailedlt — APPROVED** [review]
LGTM! ✔️
Looks Great! 💯 Thank you for another great PR! 🙇‍♂️

**Pull request merged**
