### PR TITLE
New icon: tailwindcss (plain)

### PR DESCRIPTION
**Pull request by Utkarsh1504**
Issue #579

### CODE REVIEW

**Comment by Thomas-Boi** [comment]
The optimize-svg workflow is messing up for some reason. I'll be doing some tests.

**Comment by Thomas-Boi** [comment]
@Utkarsh1504 thank you for removing those files. Each PR should only have 1 icon in them

**Review by Thomas-Boi — APPROVED** [review]
We've decided to change our optimizing workflow to something else. Since your icons look good, I'll merge it into the repo. Thank you for your work 👍

**Comment by Utkarsh1504** [comment]
Thank you @Thomas-Boi

**Pull request merged**
