### PR TITLE
new icon: gamemaker (original, original-wordmark)

### LINKED ISSUE #633: Icon request: GameMaker Studio
### About the icon
GameMaker Studio is a game engine, so it is within the domain of programmers and developers

### Links

https://www.yoyogames.com/en/legal/brand
https://en.wikipedia.org/wiki/File:GameMaker_Studio_2.svg

### PR DESCRIPTION
**Pull request by tylersernett**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #633**

## Link to prove your SVG is correct and up-to-date.

https://upload.wikimedia.org/wikipedia/en/4/4b/GameMaker_Logo.svg

### CODE REVIEW

**Review by Gautam25Raj — CHANGES_REQUESTED** [review]
- Remove height and width and replace by viewBox in `gamemaker-original.svg` and `gamemaker-original-wordmark.svg`.
- Don't use `<Image>` tag in `gamemaker-original.svg`.

**Review by Gautam25Raj — DISMISSED** [review]
Everything looks great. Nice work. 👍

**Review by lunatic-fox — COMMENTED** [review]
- Add ~`aliases`~ `altnames` property in `devicon.json` entry.

**Review by lunatic-fox — APPROVED** [review]
Icons seem to be ok now! ✔
Thank you for this contribution! 🚀

**Review by Gautam25Raj — APPROVED** [review]
Didn't saw those mistakes. Although now they seems better and optimized. 😆

**Review by Gautam25Raj — APPROVED** [review]
Didn't saw those mistakes. Although now they seems better and optimized. 😆

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀
Just wondering: are we able to add this to our icon list (see https://github.com/devicons/devicon/issues/633#issuecomment-1562408339)?

**Comment by lunatic-fox** [comment]
> Thanks! 🚀 Just wondering: are we able to add this to our icon list (see [#633 (comment)](https://github.com/devicons/devicon/issues/633#issuecomment-1562408339))?

Hmm... After reading their brand guidelines I don't think so, because it's not in accordance with **"When I can use the GameMaker logo"** and with the second item of **"General brand usage guidelines"**. Reinforced by the third item when it says:
> ***"[...] don’t change our logos in any way".***

**Comment by Panquesito7** [comment]
We could try contacting them, but their guidelines are very clear.
I think we should close the PR. Let's see what others think, though.

**Comment by PantheraRed** [comment]
> We could try contacting them, but their guidelines are very clear. I think we should close the PR. Let's see what others think, though.

I think it's best to close this PR for now. Maybe in future if they decide to change their guidelines this PR could be reopened.

**Comment by lunatic-fox** [comment]
I agree with you @Panquesito7 and @PantheraRed!

Just to be clear to you @tylersernett, this pull request is closed only due conflicts with GameMaker brand guidelines. Feel free to contribute with other icons. 🙂

Wish for the best! 🚀

**Pull request closed without merging**
