### PR TITLE
new icon: numpy (original, original-wordmark)

### PR DESCRIPTION
**Pull request by kimjiwook0129**
new icon: numpy (original, original-wordmark)

The stroke's been removed and the svgs are now in one line as requested.

### CODE REVIEW

**Review by theblobscp — COMMENTED** [review]
Looks good

**Comment by theblobscp** [comment]
If you commit on the same branch, its on the same pull request. Figure it out and remove one of them

**Comment by theblobscp** [comment]
Also you're supposed to base pull requests on the develop branch

**Comment by kimjiwook0129** [comment]
The latest pull request has been removed and I changed the branch to dev, sorry it's my first time trying to contribute to an open-source.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please re-make this PR and make it from the `develop` branch. That will remove a lot of the unneeded changes in this PR.

I'll close this PR. I'll review your new PR as soon as you submit it. Thanks. 🙂

**Pull request closed without merging**
