### PR TITLE
New Icon: solidjs (Original) vite (Original, Plain, Plain wordmark)

### PR DESCRIPTION
**Pull request by AcmeGamers**
### Adding a New Icon? 
- Add `?quick_pull=1&template=new_icon.md` to the end of your current URL and press `Enter`

### CODE REVIEW

**Comment by kilian-paquier** [comment]
Hello @AcmeGamers,

Please have a look at the contributions guidelines below :

1. https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository
2. https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md

**Comment by AcmeGamers** [comment]
> Hello @AcmeGamers,
> 
> Please have a look at the contributions guidelines below :
> 
> 1. https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository
> 2. https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md

For sure, thank you so much! ^^

**Review by Snailedlt — CHANGES_REQUESTED** [review]
Hi, please make one PR per logo. This one has both solid.js and vite

**Comment by Snailedlt** [comment]
@Panquesito7 This should be closed right?
Then @AcmeGamers can open two need Pull Requests

**Comment by AcmeGamers** [comment]
Sorry for the late reply @kilian-paquier, really thanks for the update on it! ^^ (I just saw the today's mail which led me here). @Snailedlt, yea I'm gonna do that, Kilian suggestions helped a lot on this 🙂

**Pull request closed without merging**
