### PR TITLE
new icon: embeddedc (original, plain, original-wordmark, plain-wordmark)

### PR DESCRIPTION
**Pull request by mjlabe**
Embedded C icon from PR #136

embeddedc-plain
embeddedc-plain-wordmark
embeddedc-original-wordmark
embeddedc-original

### CODE REVIEW

**Comment by amacado** [comment]
Hello @mjlabe thanks for this contribution as well! :) Can you provide us with a resource for this icon? I was not able to find any "official" design for embedded c. Is this your own creation?

**Comment by mjlabe** [comment]
Yes. I took the C icon and added an embedded chip in the background. There's no "official" icon just like C, but should we add tags like this:

https://github.com/exercism/meta/issues/27?

**Comment by Jessycah** [comment]
Hi, can someone add the Jenkins icon please? 

https://iconscout.com/icon/jenkins-2
only the original, plain black and white , needed

**Comment by mjlabe** [comment]
To request a new icon, please create a new issue. 

You can submit an icon by following the the guidelines here:

https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md

**Comment by Thomas-Boi** [comment]
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

**Comment by Thomas-Boi** [comment]
Hi @mjlabe,

I'm working on merging your PR to accept your icon. However, it seems like your branch is a bit out of date. It'd be much appreciated if you can bring the branch up to date with develop and re-push.

After a week, if the branch hasn't been updated I'll make a new PR cherry-picking your commit. This is to ensure you are still the author of the commit and get proper credits. You can also just give me permission to do it this way now.

It'd be quicker if you update the branch yourself though but whichever works 👍

**Comment by Thomas-Boi** [comment]
This PR is now remade. You can view it in #625. Thank you for your work 👍.

Also, I could not find an official logo for embedded-c. However, the one that you have look professional enough so we'll accept it. If someone let us know this is not the official logo, we will have to remove it.

**Pull request closed without merging**
