### PR TITLE
update icon: visualstudio (original, plain, line)

### PR DESCRIPTION
**Pull request by canaleal**
## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Visual Studio Website](https://visualstudio.microsoft.com/)

## Additional Notes

I was unable to find a wordmark svg for 2022 Visual Studio. It seems like only visual studio 
The dark purple color `#52218a` was used for the font SVGs.

### CODE REVIEW

**Review by lunatic-fox — APPROVED** [review]
Looks great! 👍🏼
Thank you for this contribution! 🚀
image
image

**Review by Snailedlt — DISMISSED** [review]
Great work again!
I couldn't find any official wordmark versions either, but I swear I've seen it somewhere. Perhaps we could vectorize this version?
https://archive.org/details/visualstudio-2022-community-j
image

**Comment by canaleal** [comment]
I'm gonna try to vectorize the wordmark image. Also yeah, I distinctly remember seeing a wordmark svg some time ago.

**Comment by Snailedlt** [comment]
@canaleal whenever you have time, please add the wordmark versions :)
See lunatic-fox's suggestion in the comment above

**Review by Snailedlt — APPROVED** [review]
I added the wordmark suggestion made by @lunatic-fox, and made plain + line versions of it.
Everything looks good now! ✅ 
image
image
image

**Pull request merged**
